window.categories = {
  "lang": [64, 15],
  "calendar": [4, 70, 5, 27],
  "menu-ham": [11, 10],
  "menu-open": [8, 12, 11],
  "apply-now": [39, 46, 39],
  "bewerbung": [21, 54, 47, 57, 29],
  "guide": [38, 6, 2],
  "quicklinks": [60, 45, 49, 53, 26, 46, 19],
  "footer": [24, 25],
  "contact": [41],
  "deadline": [17, 34, 7, 62],
  "rnd-link": [59, 28],
  "pdf-link": [23, 52, 9],
  "site-map": [76, 35, 22],
  "about": [42, 43]
}

window.titles = [
  "somebody once told me",
  "apply now",
  "bewerbung sose 2021",
  "bewerbung wise 1925",
  "fishing for fishies",
  "moinsen",
  "these urls will save the irl",
  "heyheyheyuff",
  "it is wednesday my dudes",
  "Alanus: Home",
  "Architektur: AKTUELLES",
  "Bard College Berlin",
  "Bauhaus-Universität Weimar: Freie Kunst (Fine Art)",
  "Bauhaus-Universität Weimar: Medienkunst/Mediengestaltung (Media Art and Design)",
  "2019_Rebrush_teaserbanner",
  "Bauhaus-Universität Weimar: News",
  "Startseite - HBK Hochschule für Bildende Künste Braunschweig",
  "Folkwang Universität der Künste",
  "Akademie der Bildenden Künste München - Bewerbung",
  "Kunstakademie Münster - University of Fine Arts Münster: &nbsp;Bewerbung",
  "Muthesius Kunsthochschule",
  "Muthesius University of Fine Arts and Design",
  "Bewerbung: Kunst im Sozialen. Kunsttherapie ",
  "Kunsttherapie, Theaterpädagogik, Kunst - Studium in Ottersberg",
  "Universität der Künste Berlin",
  "Fine Arts / Painting | Weißensee Kunsthochschule Berlin",
  "uffff"
]

window.favicons = [
  "https://www.abk-stuttgart.de/favicon-32x32.png",
  "https://www.folkwang-uni.de/fileadmin/_icons/favicon-32x32.png",
  "https://www.burg-halle.de/typo3conf/ext/nn_buha_base/Resources/Public/Images/favicon/favicon-32x32.png",
  "https://hfbk-hamburg.de/static/images/favicon-32x32.png",
  "https://www.hfbk-dresden.de/fileadmin/templates/main/Resources/Public/Images/Icons/Favicon/favicon-32x32.png",
  "https://www.hfk2020.de/includes/images/favicons/favicon-32x32.png",
  "https://www.hgb-leipzig.de/favicon-32x32.png",
  "./icons/16/favicon.png",
  "./icons/favicon.png",
  "./icons/icon1.ico",
  "./icons/icon2.ico",
  "./icons/icon4.ico",
  "./icons/icon5.ico",
  "./icons/icon6.ico",
  "./icons/icon8.ico",
  "./icons/icon11.ico",
  "./icons/icon12.ico",
  "./icons/icon13.ico",
  "./icons/icon14.ico",
  "./icons/icon15.ico",
  "./icons/icon16.ico",
  "./icons/icon17.ico",
]

window.poem = [
  "cmon",
  "i know",
  "stop looking at the console you sneaky human",
  "am i human",
  "come take a look",
  "it is now 18:04",
  "it is now 18:05",
  "it is now 18:06",
  "it is now 18:07",
  "it is now 18:08",
  "it is now 18:09",
  "it is now 18:10",
]