(function(g){var window=this;var HFa=function(a,b){a.ra("onAutonavCoundownStarted",b)},r3=function(a,b,c){var d=b.Ka();
g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.se(c?c:"mqdefault.jpg");var f=null,h=null;b instanceof g.wI&&(b.lengthText?(f=b.lengthText||null,h=b.nu||null):b.lengthSeconds&&(f=g.IM(b.lengthSeconds),h=g.IM(b.lengthSeconds,!0)));var l=!!e;e=l&&"RD"===(new g.kO(e.substr(0,2),e.substr(2))).type;var m=b instanceof g.wI?b.isLivePlayback:null,n=b instanceof g.wI?b.isUpcoming:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:
b.author,aria_label:b.lq||g.HK("Watch $TITLE",{TITLE:b.title}),duration:f,timestamp:h,url:b.yl(),is_live:m,is_upcoming:n,is_list:l,is_mix:e,background:c?"background-image: url("+c+")":"",views_and_publish_time:d.shortViewCount?d.shortViewCount+" \u2022 "+d.publishedTimeText:d.publishedTimeText,autoplayAlternativeHeader:b.oq};b instanceof g.lO&&(d.playlist_length=b.length);a.update(d)},s3=function(a){var b=a.P(),c=b.l;
g.U.call(this,{D:"a",J:"ytp-autonav-suggestion-card",R:{href:"{{url}}",target:c?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{D:"div",ga:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],R:{style:"{{background}}"},N:[{D:"div",R:{"aria-label":"{{timestamp}}"},ga:["ytp-autonav-timestamp"],Y:"{{duration}}"},{D:"div",ga:["ytp-autonav-live-stamp"],Y:"Live"},{D:"div",
ga:["ytp-autonav-upcoming-stamp"],Y:"Upcoming"},{D:"div",J:"ytp-autonav-list-overlay",N:[{D:"div",J:"ytp-autonav-mix-text",Y:"Mix"},{D:"div",J:"ytp-autonav-mix-icon"}]}]},{D:"div",ga:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Y:"{{title}}"},{D:"div",ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Y:"{{author}}"},{D:"div",ga:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Y:"{{views_and_publish_time}}"}]});this.F=a;this.suggestion=
null;this.i=c;this.va("click",this.onClick);this.va("keypress",this.l)},u3=function(a,b){b=void 0===b?!1:b;
g.U.call(this,{D:"div",J:"ytp-autonav-endscreen-countdown-container"});var c=this;this.C=b;this.l=0;var d=a.P(),e=d.l;this.F=a;this.suggestion=null;this.i=new g.U({D:"div",J:"ytp-autonav-endscreen-upnext-container",R:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},N:[{D:"div",J:"ytp-autonav-endscreen-upnext-header"},{D:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",Y:"{{autoplayAlternativeHeader}}"},
{D:"a",J:"ytp-autonav-endscreen-link-container",R:{href:"{{url}}",target:e?d.C:""},N:[{D:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",R:{style:"{{background}}"},N:[{D:"div",R:{"aria-label":"{{timestamp}}"},ga:["ytp-autonav-timestamp"],Y:"{{duration}}"},{D:"div",ga:["ytp-autonav-live-stamp"],Y:"Live"},{D:"div",ga:["ytp-autonav-upcoming-stamp"],Y:"Upcoming"}]},{D:"div",J:"ytp-autonav-endscreen-video-info",N:[{D:"div",J:"ytp-autonav-endscreen-premium-badge"},{D:"div",J:"ytp-autonav-endscreen-upnext-title",
Y:"{{title}}"},{D:"div",J:"ytp-autonav-endscreen-upnext-author",Y:"{{author}}"},{D:"div",J:"ytp-autonav-view-and-date",Y:"{{views_and_publish_time}}"},{D:"div",J:"ytp-autonav-author-and-view",Y:"{{author_and_views}}"}]}]}]});g.C(this,this.i);this.i.ca(this.element);e||this.L(this.i.ea("ytp-autonav-endscreen-link-container"),"click",this.vB);this.F.Fb(this.element,this,115127);this.F.Fb(this.i.ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.U({D:"div",J:"ytp-autonav-overlay"});
g.C(this,this.overlay);this.overlay.ca(this.element);this.u=new g.U({D:"div",J:"ytp-autonav-endscreen-button-container"});g.C(this,this.u);this.u.ca(this.element);this.cancelButton=new g.U({D:"button",ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],R:{"aria-label":"Cancel autoplay"},Y:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.ca(this.u.element);this.cancelButton.va("click",this.tJ,this);this.F.Fb(this.cancelButton.element,this,115129);this.playButton=
new g.U({D:"a",ga:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],R:{href:"{{url}}",role:"button","aria-label":"Play next video"},Y:"Play now"});g.C(this,this.playButton);this.playButton.ca(this.u.element);this.playButton.va("click",this.vB,this);this.F.Fb(this.playButton.element,this,115130);this.B=new g.D(function(){t3(c)},500);
g.C(this,this.B);this.uB();this.L(a,"autonavvisibility",this.uB)},t3=function(a){var b=v3(a),c=Math.min(a.l?Date.now()-a.l:0,b);
w3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Sg()?a.select(!0):a.Sg()&&a.B.start()},v3=function(a){var b=a.F.Tm();
return 0<=b?b:g.O(a.F.P().experiments,"autoplay_time")||1E4},w3=function(a,b){b=void 0===b?-1:b;
var c=a.i.ea("ytp-autonav-endscreen-upnext-header");g.Fe(c);if(0<=b){var d=String(b),e="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],f="Up next in $SECONDS".indexOf(e);if(0<=f){c.appendChild(g.Ee("Up next in $SECONDS".slice(0,f)));var h=g.De("span");g.qn(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Le(h,d);c.appendChild(h);c.appendChild(g.Ee("Up next in $SECONDS".slice(f+e.length)));return}}g.Le(c,"Up next")},x3=function(a,b){g.U.call(this,{D:"div",
ga:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},z3=function(a){g.U.call(this,{D:"div",
ga:["ytp-upnext","ytp-player-content"],R:{"aria-label":"{{aria_label}}"},N:[{D:"div",J:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},{D:"span",J:"ytp-upnext-top",N:[{D:"span",J:"ytp-upnext-header",Y:"Up Next"},{D:"span",J:"ytp-upnext-title",Y:"{{title}}"},{D:"span",J:"ytp-upnext-author",Y:"{{author}}"}]},{D:"a",J:"ytp-upnext-autoplay-icon",R:{role:"button",href:"{{url}}","aria-label":"Play next video"},N:[{D:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},N:[{D:"circle",
J:"ytp-svg-autoplay-circle",R:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",J:"ytp-svg-autoplay-ring",R:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",J:"ytp-svg-fill",R:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",J:"ytp-upnext-bottom",N:[{D:"span",J:"ytp-upnext-cancel"},{D:"span",J:"ytp-upnext-paused",Y:"Auto-play is paused"}]}]});
this.api=a;this.cancelButton=null;this.C=this.ea("ytp-svg-autoplay-ring");this.u=this.notification=this.i=this.suggestion=null;this.B=new g.D(this.qt,5E3,this);this.l=0;var b=this.ea("ytp-upnext-cancel");this.cancelButton=new g.U({D:"button",ga:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:"0","aria-label":"Cancel autoplay"},Y:"Cancel"});g.C(this,this.cancelButton);this.cancelButton.va("click",this.uJ,this);this.cancelButton.ca(b);this.cancelButton&&this.api.Fb(this.cancelButton.element,this,
115129);g.C(this,this.B);this.api.Fb(this.element,this,18788);b=this.ea("ytp-upnext-autoplay-icon");this.L(b,"click",this.vJ);this.api.Fb(b,this,115130);this.wB();this.L(a,"autonavvisibility",this.wB);this.L(a,"mdxnowautoplaying",this.VN);this.L(a,"mdxautoplaycanceled",this.WN);this.L(a,"mdxautoplayupnext",this.sH);y3(this)&&(a=(a=g.cO(this.api.Ra()))?a.lL():null)&&this.sH(a);g.K(this.element,"ytp-upnext-mobile",this.api.P().i)},y3=function(a){return 3===a.api.getPresentingPlayerType()},IFa=function(a,
b){return b?b:0<=a.api.Tm()?a.api.Tm():g.O(a.api.P().experiments,"autoplay_time")||1E4},A3=function(a,b){var c=IFa(a,b),d=Math,e=d.min;
var f=(0,g.M)()-a.l;d=e.call(d,f,c);c=0===c?1:Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&a.Sg()&&!y3(a)?a.select(!0):a.Sg()&&a.i.start()},B3=function(a){x3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=this.suggestions=null;this.table=new g.U({D:"div",J:"ytp-suggestion-panel",N:[{D:"div",ga:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Y:"More videos"}]});this.I=new g.U({D:"div",J:"ytp-suggestions-container"});this.videos=[];this.u=null;this.C=this.G=!1;this.l=new u3(this.player);g.C(this,this.l);this.l.ca(this.element);a.getVideoData().oc?this.i=this.l:(this.i=new z3(a),g.gO(this.player,this.i.element,4),g.C(this,this.i));this.overlay=new g.U({D:"div",
J:"ytp-autonav-overlay-cancelled-state"});g.C(this,this.overlay);this.overlay.ca(this.element);this.B=new g.iO(this);g.C(this,this.B);g.C(this,this.table);this.table.ca(this.element);this.table.show();g.C(this,this.I);this.I.ca(this.table.element);this.hide()},JFa=function(a,b){return g.Kc(b.suggestions,function(c){c=g.hR(a.player.P(),c);
g.C(a,c);return c})},C3=function(a){var b=a.sd();
b!==a.C&&(a.C=b,a.player.S("autonavvisibility"),a.C?(a.l!==a.i&&a.l.hide(),a.table.hide()):(a.l!==a.i&&a.l.show(),a.table.show()))},D3=function(a){x3.call(this,a,"subscribecard-endscreen");
this.i=new g.U({D:"div",J:"ytp-subscribe-card",N:[{D:"img",J:"ytp-author-image",R:{src:"{{profilePicture}}"}},{D:"div",J:"ytp-subscribe-card-right",N:[{D:"div",J:"ytp-author-name",Y:"{{author}}"},{D:"div",J:"html5-subscribe-button-container"}]}]});g.C(this,this.i);this.i.ca(this.element);var b=a.getVideoData();this.subscribeButton=new g.tP("Subscribe",null,"Unsubscribe",null,!0,!1,b.Eg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.subscribeButton);this.subscribeButton.ca(this.i.ea("html5-subscribe-button-container"));
this.L(a,"videodatachange",this.oa);this.oa();this.hide()},E3=function(a){var b=a.P(),c=g.EA||g.zg?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.i&&e.push("ytp-videowall-show-text");g.U.call(this,{D:"a",ga:e,R:{href:"{{url}}",target:d?b.C:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},N:[{D:"div",J:"ytp-videowall-still-image",R:{style:"{{background}}"}},{D:"span",J:"ytp-videowall-still-info",N:[{D:"span",J:"ytp-videowall-still-info-bg",N:[{D:"span",J:"ytp-videowall-still-info-content",R:c,N:[{D:"span",J:"ytp-videowall-still-info-title",Y:"{{title}}"},{D:"span",J:"ytp-videowall-still-info-author",
Y:"{{author_and_views}}"},{D:"span",J:"ytp-videowall-still-info-live",Y:"Live"},{D:"span",J:"ytp-videowall-still-info-duration",Y:"{{duration}}"}]}]}]},{D:"span",ga:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],N:[{D:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",J:"ytp-videowall-still-listlabel-length",N:[" (",{D:"span",Y:"{{playlist_length}}"},")"]}]},{D:"span",ga:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],N:[{D:"span",
J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",J:"ytp-videowall-still-listlabel-length",Y:" (50+)"}]}]});this.suggestion=null;this.l=d;this.api=a;this.i=new g.iO(this);g.C(this,this.i);this.va("click",this.onClick);this.va("keypress",this.u);this.i.L(a,"videodatachange",this.La);a.Mg(this.element,this);this.La()},F3=function(a){x3.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.u=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.I=!1;this.K=null;this.l=new g.iO(this);g.C(this,this.l);this.G=new g.D(function(){g.I(b.element,"ytp-show-tiles")},0);
g.C(this,this.G);var c=new g.U({D:"button",ga:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":"Previous"},N:[g.gM()]});g.C(this,c);c.ca(this.element);c.va("click",this.zJ,this);this.table=new g.$L({D:"div",J:"ytp-endscreen-content"});g.C(this,this.table);this.table.ca(this.element);c=new g.U({D:"button",ga:["ytp-button","ytp-endscreen-next"],R:{"aria-label":"Next"},N:[g.hM()]});g.C(this,c);c.ca(this.element);c.va("click",this.yJ,this);a.getVideoData().oc?this.i=new u3(a,!0):this.i=new z3(a);
g.C(this,this.i);g.gO(this.player,this.i.element,4);this.hide()},G3=function(a){return g.hO(a.player)&&a.nq()&&!a.B},KFa=function(a,b){return g.Kc(b.suggestions,function(c){c=g.hR(a.F.P(),c);
g.C(a,c);return c})},H3=function(a){var b=a.sd();
b!==a.I&&(a.I=b,a.player.S("autonavvisibility"))},I3=function(a){g.sO.call(this,a);
var b=this;this.endScreen=null;this.i=this.l=this.u=!1;this.listeners=new g.iO(this);g.C(this,this.listeners);this.env=a.P();LFa(a)?(this.u=!0,MFa(this),this.i?this.endScreen=new B3(a):this.endScreen=new F3(this.player)):this.env.Ac?this.endScreen=new D3(this.player):this.endScreen=new x3(this.player);g.C(this,this.endScreen);g.gO(this.player,this.endScreen.element,4);NFa(this);this.listeners.L(a,"videodatachange",this.La,this);this.listeners.L(a,g.uG("endscreen"),function(c){b.wd(c)});
this.listeners.L(a,g.vG("endscreen"),function(c){b.hf(c)})},MFa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.We&&a.l===b.oc)return!1;a.i=b.We;a.l=b.oc;return!0},LFa=function(a){a=a.P();
return a.ib&&!a.Ac},NFa=function(a){a.player.Le("endscreen");
var b=a.player.getVideoData();b=new g.rG(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.rG(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});a.player.Gd([b,c])};
g.$N.prototype.Tm=g.ca(4,function(){return this.app.Tm()});
g.hW.prototype.Tm=g.ca(3,function(){return this.getVideoData().tG});
g.u(s3,g.U);s3.prototype.select=function(){(this.F.Fi(this.suggestion.Ka().videoId,this.suggestion.zd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Ix||void 0)||this.F.W("web_player_endscreen_double_log_fix_killswitch"))&&this.F.sb(this.element)};
s3.prototype.onClick=function(a){g.LO(a,this.F,this.i,this.suggestion.zd||void 0)&&this.select()};
s3.prototype.l=function(a){switch(a.keyCode){case 13:case 32:g.lp(a)||(this.select(),g.kp(a))}};
s3.prototype.Td=function(a){g.K(this.element,"ytp-suggestion-card-with-margin",a)};g.u(u3,g.U);g.k=u3.prototype;g.k.eq=function(a){this.suggestion!==a&&(this.suggestion=a,r3(this.i,a),this.playButton.wa("url",this.suggestion.yl()),this.Td())};
g.k.Td=function(){var a=this.F.gj(!0,this.F.isFullscreen());g.K(this.element,"ytp-autonav-endscreen-small-mode",this.Je(a));g.K(this.element,"ytp-autonav-endscreen-is-premium",!!this.suggestion&&!!this.suggestion.jv);g.K(this.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!this.F.sd());g.K(this.F.getRootNode(),"countdown-running",this.Sg());g.K(this.element,"ytp-player-content",this.F.sd());g.wg(this.overlay.element,{width:a.width+"px"});if(!this.Sg()){this.F.sd()?w3(this,Math.round(v3(this)/
1E3)):w3(this);a=!!this.suggestion&&!!this.suggestion.oq;var b=this.F.sd()||!a;g.K(this.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!b&&a);g.K(this.element,"ytp-autonav-endscreen-upnext-no-alternative-header",b&&!a);g.cM(this.u,this.F.sd())}};
g.k.Sg=function(){return 0<this.l};
g.k.Fp=function(){this.Sg()||(this.l=Date.now(),t3(this),HFa(this.F,v3(this)),g.K(this.F.getRootNode(),"countdown-running",this.Sg()))};
g.k.vn=function(){this.Bk();t3(this)};
g.k.Bk=function(){this.Sg()&&(this.B.stop(),this.l=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Bk()};
g.k.vB=function(a){g.LO(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.sb(this.playButton.element):a.currentTarget===this.i.ea("ytp-autonav-endscreen-link-container")&&(a=this.i.ea("ytp-autonav-endscreen-link-container"),this.F.Ma(a,!0),this.F.sb(a)),this.select())};
g.k.tJ=function(){this.F.sb(this.cancelButton.element);g.bO(this.F,!0)};
g.k.uB=function(){var a=this.F.sd();this.C&&this.Xa!==a&&g.cM(this,a);this.Td();this.F.Ma(this.element,a);this.F.Ma(this.cancelButton.element,a);this.F.Ma(this.i.ea("ytp-autonav-endscreen-link-container"),a);this.F.Ma(this.playButton.element,a)};
g.k.Je=function(a){return 400>a.width||459>a.height};g.u(x3,g.U);g.k=x3.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.nq=function(){return!1};
g.k.sd=function(){return!1};
g.k.nE=function(){return!1};g.u(z3,g.U);g.k=z3.prototype;g.k.qt=function(){this.notification&&(this.B.stop(),this.Db(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.k.eq=function(a){this.suggestion=a;r3(this,a,"hqdefault.jpg")};
g.k.wB=function(){g.cM(this,this.api.sd());this.api.Ma(this.element,this.api.sd());this.api.Ma(this.ea("ytp-upnext-autoplay-icon"),this.api.sd());this.cancelButton&&this.api.Ma(this.cancelButton.element,this.api.sd())};
g.k.iO=function(){window.focus();this.qt()};
g.k.Fp=function(a){var b=this;this.Sg()||(g.Mo("a11y-announce","Up Next "+this.suggestion.title),this.l=(0,g.M)(),this.i=new g.D(function(){A3(b,a)},25),A3(this,a),HFa(this.api,IFa(this,a)));
g.tn(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.U.prototype.hide.call(this)};
g.k.Sg=function(){return!!this.i};
g.k.vn=function(){this.Bk();this.l=(0,g.M)();A3(this);g.I(this.element,"ytp-upnext-autoplay-paused")};
g.k.Bk=function(){this.Sg()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(g.P(this.api.P().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Ka(),this.qt(),this.notification=new Notification("Up Next",{body:b.title,icon:b.se()}),this.u=this.L(this.notification,"click",this.iO),this.B.start())}this.Bk();this.api.nextVideo(!1,a)};
g.k.vJ=function(a){!g.Ke(this.cancelButton.element,g.gp(a))&&g.LO(a,this.api)&&(this.api.sd()&&this.api.sb(this.ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.uJ=function(){this.api.sd()&&this.cancelButton&&this.api.sb(this.cancelButton.element);g.bO(this.api,!0)};
g.k.VN=function(a){y3(this);this.show();this.Fp(a)};
g.k.sH=function(a){y3(this);this.suggestion&&this.suggestion.Ka().videoId===a.Ka().videoId||this.eq(a)};
g.k.WN=function(){y3(this);this.Bk();this.hide()};
g.k.aa=function(){this.Bk();this.qt();g.U.prototype.aa.call(this)};g.u(B3,x3);g.k=B3.prototype;g.k.create=function(){x3.prototype.create.call(this);this.B.L(this.player,"appresize",this.Td);this.B.L(this.player,"onVideoAreaChange",this.Td);this.B.L(this.player,"videodatachange",this.La);this.B.L(this.player,"autonavchange",this.xB);this.B.L(this.player,"autonavcancel",this.wJ);this.La()};
g.k.show=function(){x3.prototype.show.call(this);(this.G||this.u&&this.u!==this.videoData.clientPlaybackNonce)&&g.bO(this.player,!1);g.hO(this.player)&&this.nq()&&!this.u?(C3(this),2===this.videoData.autonavState?this.player.P().W("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Fp():3===this.videoData.autonavState&&this.i.vn()):(g.bO(this.player,!0),C3(this));this.Td()};
g.k.hide=function(){x3.prototype.hide.call(this);this.i.vn();C3(this)};
g.k.Td=function(){var a=this.player.gj(!0,this.player.isFullscreen());C3(this);this.l.Td();g.K(this.element,"ytp-autonav-cancelled-small-mode",this.Je(a));g.K(this.element,"ytp-autonav-cancelled-tiny-mode",this.iu(a));g.K(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.wg(this.overlay.element,{width:a.width+"px"});if(!this.C){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){b=g.q(b.value);var c=b.next().value;b.next().value.Td(1===c%2)}}};
g.k.La=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((this.suggestions=JFa(this,a))&&this.suggestions.length)for(this.i.eq(this.suggestions[0]),this.i!==this.l&&this.l.eq(this.suggestions[0]),a=0;a<OFa.length;++a){var b=OFa[a];if(this.suggestions&&this.suggestions[b]){this.videos[a]=new s3(this.player);var c=this.videos[a];b=this.suggestions[b];c.suggestion!==b&&(c.suggestion=b,r3(c,b));g.C(this,this.videos[a]);this.videos[a].ca(this.I.element)}}this.Td()}};
g.k.xB=function(a){1===a?(this.G=!1,this.u=this.videoData.clientPlaybackNonce,this.i.Bk(),this.Xa&&this.Td()):(this.G=!0,this.sd()&&(2===a?this.i.Fp():3===a&&this.i.vn()))};
g.k.wJ=function(a){a?this.xB(1):(this.u=null,this.G=!1)};
g.k.nq=function(){return 1!==this.videoData.autonavState};
g.k.Je=function(a){return(910>a.width||459>a.height)&&!this.iu(a)&&!(400>=a.width||360>=a.height)};
g.k.iu=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.sd=function(){return this.Xa&&g.hO(this.player)&&this.nq()&&!this.u};
var OFa=[1,3,2,4];g.u(D3,x3);D3.prototype.oa=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.cg,author:a.author});this.subscribeButton.channelId=a.Eg;var b=this.subscribeButton;a.subscribed?b.l():b.u()};g.u(E3,g.U);E3.prototype.select=function(){(this.api.Fi(this.suggestion.Ka().videoId,this.suggestion.zd,this.suggestion.getPlaylistId(),void 0,void 0,this.suggestion.Ix||void 0)||this.api.W("web_player_endscreen_double_log_fix_killswitch"))&&this.api.sb(this.element)};
E3.prototype.onClick=function(a){g.LO(a,this.api,this.l,this.suggestion.zd||void 0)&&this.select()};
E3.prototype.u=function(a){switch(a.keyCode){case 13:case 32:g.lp(a)||(this.select(),g.kp(a))}};
E3.prototype.La=function(){var a=this.api.getVideoData(),b=this.api.P();this.l=a.C?!1:b.l};g.u(F3,x3);g.k=F3.prototype;g.k.create=function(){x3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=KFa(this,a),this.videoData=a);this.Td();this.l.L(this.player,"appresize",this.Td);this.l.L(this.player,"onVideoAreaChange",this.Td);this.l.L(this.player,"videodatachange",this.La);this.l.L(this.player,"autonavchange",this.tw);this.l.L(this.player,"autonavcancel",this.xJ);a=this.videoData.autonavState;a!==this.K&&this.tw(a);this.l.L(this.element,"transitionend",this.vP)};
g.k.destroy=function(){g.Lt(this.l);g.$f(this.stills);this.stills=[];this.suggestions=null;x3.prototype.destroy.call(this);g.tn(this.element,"ytp-show-tiles");this.G.stop();this.K=this.videoData.autonavState};
g.k.nq=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){x3.prototype.show.call(this);g.tn(this.element,"ytp-show-tiles");this.player.P().i?g.mn(this.G):this.G.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.bO(this.player,!1);G3(this)?(H3(this),2===this.videoData.autonavState?this.player.P().W("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Fp():3===this.videoData.autonavState&&this.i.vn()):(g.bO(this.player,!0),H3(this))};
g.k.hide=function(){x3.prototype.hide.call(this);this.i.vn();H3(this)};
g.k.vP=function(a){g.gp(a)===this.element&&this.Td()};
g.k.Td=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=this.F.gj(!0,this.F.isFullscreen()),b=g.XN(this.F);b&&(b=b.te()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,w=e<=h-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=
r*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Lg(a,m,n);g.wg(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.eq(this.suggestions[0]);this.i instanceof u3&&this.i.Td();g.K(this.element,"ytp-endscreen-takeover",G3(this));H3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?
r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.ae(p+this.u,l),0!==r){t=this.stills[c];t||(t=new E3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-w-4,F=Math.floor(m*(f+r)/b)-x-4;g.Eg(t.element,x,w);g.Lg(t.element,F,y);g.wg(t.element,"transitionDelay",(h+f)/20+"s");g.K(t.element,"ytp-videowall-still-mini",1===r);g.K(t.element,"ytp-videowall-still-large",2<r);r=t;p=this.suggestions[p];r.suggestion!==p&&(r.suggestion=
p,t=r.api.P(),w=g.rn(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",r3(r,p,w),g.MC(t)&&(t=p.yl(),t=g.Jd(t,g.pP("emb_rel_end")),r.wa("url",t)),(p=(p=p.zd)&&p.itct)&&r.api.Vl(r.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.He(e.element),g.Zf(e);this.stills.length=c}};
g.k.La=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.u=0,this.suggestions=KFa(this,a),this.videoData=a,this.Td())};
g.k.yJ=function(){this.u+=this.stills.length;this.Td()};
g.k.zJ=function(){this.u-=this.stills.length;this.Td()};
g.k.nE=function(){return this.i.Sg()};
g.k.tw=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Bk(),this.Xa&&this.Td()):(this.C=!0,this.Xa&&G3(this)&&(2===a?this.i.Fp():3===a&&this.i.vn()))};
g.k.xJ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Ma(this.stills[a].element,!0);this.tw(1)}else this.B=null,this.C=!1;this.Td()};
g.k.sd=function(){return this.Xa&&G3(this)};g.u(I3,g.sO);g.k=I3.prototype;g.k.Dn=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!LFa(this.player)||b;var c=a.Qc||g.WC(a.B),d=this.player.Oq();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.sd=function(){return this.endScreen.sd()};
g.k.UL=function(){return this.sd()?this.endScreen.nE():!1};
g.k.aa=function(){this.player.Le("endscreen");g.sO.prototype.aa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.SD;if(b&&b.videoId){var c=this.player.Ra().Zc.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].id&&!a.PB?a=!1:(this.player.Fi(b.videoId,void 0,void 0,!0,!0,b),c&&c.qu("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.sO.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.sO.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.wd=function(a){this.Dn()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.hf=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.La=function(){NFa(this);this.u&&MFa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new B3(this.player):this.endScreen=new F3(this.player),g.C(this,this.endScreen),g.gO(this.player,this.endScreen.element,4))};g.yO.endscreen=I3;})(_yt_player);
