(function(g){var window=this;var tGa=function(a,b){return g.Kb(a,b)},t4=function(a,b,c){a.u.set(b,c)},u4=function(a){t4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.A()).toString(36));
return a},v4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.u,b,c)},uGa=function(a,b){var c=[];
g.mj(b,function(d){try{var e=g.$n.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Zn(e)&&c.push(d)},a);
return c},vGa=function(a,b){var c=uGa(a,b);
g.zb(c,function(d){g.$n.prototype.remove.call(this,d)},a)},wGa=function(a){if(a.T){if(a.T.locationOverrideToken)return{locationOverrideToken:a.T.locationOverrideToken};
if(null!=a.T.latitudeE7&&null!=a.T.longitudeE7)return{latitudeE7:a.T.latitudeE7,longitudeE7:a.T.longitudeE7}}return null},xGa=function(a,b){g.eb(a,b)||a.push(b)},w4=function(a){var b=0,c;
for(c in a)b++;return b},yGa=function(a,b){var c=b instanceof g.Ac?b:g.Gc(b,/^data:image\//i.test(b));
a.src=g.Bc(c)},x4=function(){},zGa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},AGa=function(a){if(a.rg&&"function"==typeof a.rg)return a.rg();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Hb(a)},BGa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.wh&&"function"==typeof a.wh)var c=a.wh();else if(a.rg&&"function"==typeof a.rg)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Ib(a);d=AGa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},CGa=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.l=d);return e},y4=function(a,b){g.Io[a]=!0;
var c=g.Go();c&&c.publish.apply(c,arguments);g.Io[a]=!1},z4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",DGa(this,a.capabilities||""),EGa(this,a.experiments||""))},DGa=function(a,b){a.capabilities.clear();
g.Ie(b.split(","),g.Qa(tGa,FGa)).forEach(function(c){a.capabilities.add(c)})},EGa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},A4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},B4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},GGa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},HGa=function(a){return new A4(a)},IGa=function(a){return Array.isArray(a)?g.Kc(a,HGa):[]},C4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},D4=function(a){return Array.isArray(a)?"["+g.Kc(a,C4).join(",")+"]":"null"},E4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},JGa=function(a){return g.Kc(a,function(b){return{key:b.id,
name:b.name}})},F4=function(a,b){return g.ab(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},G4=function(a,b){return g.ab(a,function(c){return B4(c,b)})},KGa=function(){var a=(0,g.xu)();
a&&vGa(a,a.i.Qj(!0))},H4=function(){var a=g.Au("yt-remote-connected-devices")||[];
g.wb(a);return a},LGa=function(a){if(g.fb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Kc(a,function(d,e){return 0==e?d:d.substring(c.length)})},MGa=function(a){g.zu("yt-remote-connected-devices",a,86400)},J4=function(){if(I4)return I4;
var a=g.Au("yt-remote-device-id");a||(a=E4(),g.zu("yt-remote-device-id",a,31536E3));for(var b=H4(),c=1,d=a;g.eb(b,d);)c++,d=a+"#"+c;return I4=d},K4=function(){var a=H4(),b=J4();
g.eb(a,b);g.Cu()&&g.yb(a,b);a=LGa(a);if(g.fb(a))try{g.Cq("remote_sid")}catch(c){}else try{g.Aq("remote_sid",a.join(","),-1)}catch(c){}},NGa=function(){return g.Au("yt-remote-session-browser-channel")},OGa=function(){return g.Au("yt-remote-local-screens")||[]},PGa=function(){g.zu("yt-remote-lounge-token-expiration",!0,86400)},QGa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Kc(OGa(),function(d){return d.loungeToken}),c=g.Kc(a,function(d){return d.loungeToken});
g.vh(c,function(d){return!g.eb(b,d)})&&PGa();
g.zu("yt-remote-local-screens",a,31536E3)},RGa=function(a,b){g.zu("yt-remote-session-browser-channel",a);
g.zu("yt-remote-session-screen-id",b);var c=H4(),d=J4();g.eb(c,d)||c.push(d);MGa(c);K4()},L4=function(a){a||(g.Bu("yt-remote-session-screen-id"),g.Bu("yt-remote-session-video-id"));
K4();a=H4();g.jb(a,J4());MGa(a)},SGa=function(){if(!M4){var a=g.ko();
a&&(M4=new g.Ln(a))}},TGa=function(){SGa();
return M4?!!M4.get("yt-remote-use-staging-server"):!1},UGa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},VGa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},N4=function(a){a.length?WGa(a.shift(),function(){N4(a)}):O4()},XGa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},WGa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.gd(d,g.ug(a));(document.head||document.documentElement).appendChild(d)},O4=function(){var a=VGa();
a&&a(!1,"No cast extension found")},ZGa=function(){if(YGa){var a=2,b=VGa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;WGa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",O4,c)}},$Ga=function(){ZGa();
var a=(a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/))?parseInt(a[1],10):0;var b=[];if(0!=a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}b.push("//www.gstatic.com/eureka/clank/cast_sender.js");N4(b)},P4=function(a,b,c){g.B.call(this);
this.G=null!=c?(0,g.z)(a,c):a;this.Gf=b;this.C=(0,g.z)(this.HJ,this);this.i=!1;this.l=0;this.u=this.bb=null;this.B=[]},Q4=function(a,b,c){g.B.call(this);
this.B=null!=c?a.bind(c):a;this.Gf=b;this.u=null;this.i=!1;this.l=0;this.bb=null},R4=function(a){a.bb=g.Mm(function(){a.bb=null;
a.i&&!a.l&&(a.i=!1,R4(a))},a.Gf);
var b=a.u;a.u=null;a.B.apply(null,b)},S4=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return zGa(a)},T4=function(){},U4=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},W4=function(a){V4.dispatchEvent(new aHa(V4,a))},aHa=function(a){g.Il.call(this,"statevent",a)},X4=function(){},bHa=function(){},dHa=function(a){return(a=cHa(a))?new ActiveXObject(a):new XMLHttpRequest},cHa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},Y4=function(a,b,c,d){this.i=a;
this.l=b;this.K=c;this.I=d||1;this.C=45E3;this.B=new g.v_(this);this.u=new g.Lm;this.u.setInterval(250)},fHa=function(a,b,c){a.Ip=1;
a.Xk=u4(b.clone());a.yn=c;a.G=!0;eHa(a,null)},Z4=function(a,b,c,d,e){a.Ip=1;
a.Xk=u4(b.clone());a.yn=null;a.G=c;e&&(a.GG=!1);eHa(a,d)},eHa=function(a,b){a.yp=g.A();
$4(a);a.Rl=a.Xk.clone();v4(a.Rl,"t",a.I);a.Hs=0;a.ze=a.i.zx(a.i.hs()?b:null);0<a.ww&&(a.Tu=new Q4((0,g.z)(a.EH,a,a.ze),a.ww));a.B.va(a.ze,"readystatechange",a.gQ);var c=a.mm?g.Rb(a.mm):{};a.yn?(a.Fv="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.ze.send(a.Rl,a.Fv,a.yn,c)):(a.Fv="GET",a.GG&&!g.ye&&(c.Connection="close"),a.ze.send(a.Rl,a.Fv,null,c));a.i.ii(1)},iHa=function(a,b,c){for(var d=!0;!a.Jm&&a.Hs<c.length;){var e=gHa(a,c);
if(e==a5){4==b&&(a.Rk=4,W4(15),d=!1);break}else if(e==hHa){a.Rk=4;W4(16);d=!1;break}else b5(a,e)}4==b&&0==c.length&&(a.Rk=1,W4(17),d=!1);a.zi=a.zi&&d;d||(c5(a),d5(a))},gHa=function(a,b){var c=a.Hs,d=b.indexOf("\n",c);
if(-1==d)return a5;c=Number(b.substring(c,d));if(isNaN(c))return hHa;d+=1;if(d+c>b.length)return a5;var e=b.substr(d,c);a.Hs=d+c;return e},kHa=function(a,b){a.yp=g.A();
$4(a);var c=b?window.location.hostname:"";a.Rl=a.Xk.clone();t4(a.Rl,"DOMAIN",c);t4(a.Rl,"t",a.I);try{a.Di=new ActiveXObject("htmlfile")}catch(n){c5(a);a.Rk=7;W4(22);d5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var h=c.charAt(f);if("<"==h)h=e+"\\x3c";else if(">"==h)h=e+"\\x3e";else{if(h in e5)h=e5[h];else if(h in jHa)h=e5[h]=jHa[h];else{var l=h.charCodeAt(0);if(31<l&&127>l)var m=h;else{if(256>l){if(m="\\x",16>l||256<l)m+="0"}else m="\\u",4096>l&&(m+="0");m+=l.toString(16).toUpperCase()}h=
e5[h]=m}h=e+h}e=h}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.dd(g.cc("b/12014412"),d+"</body></html>");a.Di.open();a.Di.write(g.$c(c));a.Di.close();a.Di.parentWindow.m=(0,g.z)(a.yP,a);a.Di.parentWindow.d=(0,g.z)(a.RF,a,!0);a.Di.parentWindow.rpcClose=(0,g.z)(a.RF,a,!1);c=a.Di.createElement("DIV");a.Di.parentWindow.document.body.appendChild(c);d=g.Fc(a.Rl.toString());d=g.ld(g.Bc(d));d=g.dd(g.cc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.ed(c,d);a.i.ii(1)},$4=function(a){a.BA=g.A()+a.C;
lHa(a,a.C)},lHa=function(a,b){if(null!=a.Op)throw Error("WatchDog timer not null");
a.Op=U4((0,g.z)(a.GP,a),b)},f5=function(a){a.Op&&(g.v.clearTimeout(a.Op),a.Op=null)},d5=function(a){a.i.zB()||a.Jm||a.i.Ws(a)},c5=function(a){f5(a);
g.Zf(a.Tu);a.Tu=null;a.u.stop();g.RAa(a.B);if(a.ze){var b=a.ze;a.ze=null;b.abort();b.dispose()}a.Di&&(a.Di=null)},b5=function(a,b){try{a.i.IF(a,b),a.i.ii(4)}catch(c){}},nHa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;mHa(a,b,function(h){h?c(!0):g.v.setTimeout(function(){nHa(a,b,c,d,f)},f)})}},mHa=function(a,b,c){var d=new Image;
d.onload=function(){try{g5(d),c(!0)}catch(e){}};
d.onerror=function(){try{g5(d),c(!1)}catch(e){}};
d.onabort=function(){try{g5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{g5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
yGa(d,a)},g5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},h5=function(a){g.bm.call(this);
this.headers=new g.Om;this.ba=a||null;this.B=!1;this.Z=this.i=null;this.xa=this.T="";this.G=0;this.u="";this.C=this.ha=this.K=this.da=!1;this.I=0;this.U=null;this.Aa="";this.V=this.fa=!1},oHa=function(a){return g.we&&g.Yd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},pHa=function(a){return"content-type"==a.toLowerCase()},rHa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;qHa(a);i5(a)},qHa=function(a){a.da||(a.da=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},tHa=function(a){if(a.B&&"undefined"!=typeof g.y_)if(a.Z[1]&&4==j5(a)&&2==a.getStatus())k5(a,"Local request error detected and ignored");
else if(a.K&&4==j5(a))g.Mm(a.FF,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){k5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.ud(1,String(a.T));if(!f&&g.v.self&&g.v.self.location){var h=g.v.self.location.protocol;f=h.substr(0,h.length-1)}e=!sHa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<j5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";qHa(a)}}finally{i5(a)}}},i5=function(a,b){if(a.i){uHa(a);
var c=a.i,d=a.Z[0]?g.Ja:null;a.i=null;a.Z=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},uHa=function(a){a.i&&a.V&&(a.i.ontimeout=null);
a.U&&(g.v.clearTimeout(a.U),a.U=null)},j5=function(a){return a.i?a.i.readyState:0},l5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},k5=function(a,b){return b+" ["+a.xa+" "+a.T+" "+a.getStatus()+"]"},vHa=function(a){this.i=a;
this.l=new T4},wHa=function(a){var b=m5(a.i,a.qq,"/mail/images/cleardot.gif");
u4(b);nHa(b.toString(),5E3,(0,g.z)(a.zK,a),3,2E3);a.ii(1)},o5=function(a){var b=a.i.K;
if(null!=b)W4(5),b?(W4(11),n5(a.i,a,!1)):(W4(12),n5(a.i,a,!0));else if(a.Cg=new Y4(a,void 0,void 0,void 0),a.Cg.mm=a.xw,b=a.i,b=m5(b,b.hs()?a.gq:null,a.yw),W4(5),!g.we||g.Zd(10))v4(b,"TYPE","xmlhttp"),Z4(a.Cg,b,!1,a.gq,!1);else{v4(b,"TYPE","html");var c=a.Cg;a=!!a.gq;c.Ip=3;c.Xk=u4(b.clone());kHa(c,a)}},p5=function(a,b,c){this.Ja=1;
this.i=[];this.u=[];this.B=new T4;this.I=a||null;this.K=null!=b?b:null;this.C=c||!1},xHa=function(a,b){this.i=a;
this.map=b;this.context=null},yHa=function(a,b,c,d){g.Il.call(this,"timingevent",a);
this.size=b;this.Vr=d},zHa=function(a){g.Il.call(this,"serverreachability",a)},CHa=function(a){AHa(a);
if(3==a.Ja){var b=a.Cr++,c=a.Ct.clone();t4(c,"SID",a.l);t4(c,"RID",b);t4(c,"TYPE","terminate");q5(a,c);b=new Y4(a,a.l,b,void 0);b.Ip=2;b.Xk=u4(c.clone());yGa(new Image,b.Xk.toString());b.yp=g.A();$4(b)}BHa(a)},DHa=function(a){a.UK(1,0);
a.Ct=m5(a,null,a.zw);r5(a)},AHa=function(a){a.bl&&(a.bl.abort(),a.bl=null);
a.Wd&&(a.Wd.cancel(),a.Wd=null);a.Rj&&(g.v.clearTimeout(a.Rj),a.Rj=null);s5(a);a.ng&&(a.ng.cancel(),a.ng=null);a.ol&&(g.v.clearTimeout(a.ol),a.ol=null)},EHa=function(a,b){if(0==a.Ja)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new xHa(a.vM++,b));2!=a.Ja&&3!=a.Ja||r5(a)},FHa=function(a){var b=0;
a.Wd&&b++;a.ng&&b++;return b},r5=function(a){a.ng||a.ol||(a.ol=U4((0,g.z)(a.PF,a),0),a.Bo=0)},HHa=function(a,b){if(1==a.Ja){if(!b){a.Cr=Math.floor(1E5*Math.random());
var c=a.Cr++,d=new Y4(a,"",c,void 0);d.mm=a.Ki;var e=t5(a),f=a.Ct.clone();t4(f,"RID",c);t4(f,"CVER","1");q5(a,f);fHa(d,f,e);a.ng=d;a.Ja=2}}else 3==a.Ja&&(b?GHa(a,b):0==a.i.length||a.ng||GHa(a))},GHa=function(a,b){if(b)if(6<a.Km){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Cr-1;var d=t5(a)}else c=b.K,d=b.yn;else c=a.Cr++,d=t5(a);var e=a.Ct.clone();t4(e,"SID",a.l);t4(e,"RID",c);t4(e,"AID",a.Vo);q5(a,e);c=new Y4(a,a.l,c,a.Bo+1);c.mm=a.Ki;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ng=c;fHa(c,e,d)},q5=function(a,b){if(a.wf){var c=a.wf.nD();
c&&g.Bb(c,function(d,e){t4(b,e,d)})}},t5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Km&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Qn:e.Qn},f++){e.Qn=a.i[f].i;var h=a.i[f].map;e.Qn=6>=a.Km?f:e.Qn-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.Qn+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Qn+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},IHa=function(a){a.Wd||a.Rj||(a.G=1,a.Rj=U4((0,g.z)(a.OF,a),0),a.ko=0)},u5=function(a){if(a.Wd||a.Rj||3<=a.ko)return!1;
a.G++;a.Rj=U4((0,g.z)(a.OF,a),JHa(a,a.ko));a.ko++;return!0},n5=function(a,b,c){a.Dv=c;
a.Li=b.Oj;a.C||DHa(a)},s5=function(a){null!=a.Rm&&(g.v.clearTimeout(a.Rm),a.Rm=null)},JHa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},v5=function(a,b){if(2==b||9==b){var c=null;
a.wf&&(c=null);var d=(0,g.z)(a.PQ,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),u4(c));mHa(c.toString(),1E4,d)}else W4(2);KHa(a,b)},KHa=function(a,b){a.Ja=0;
a.wf&&a.wf.CC(b);BHa(a);AHa(a)},BHa=function(a){a.Ja=0;
a.Li=-1;if(a.wf)if(0==a.u.length&&0==a.i.length)a.wf.ix();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.wf.ix(b)}},m5=function(a,b,c){var d=g.Zm(c);
if(""!=d.i)b&&g.Tm(d,b+"."+d.i),g.Um(d,d.B);else{var e=window.location;d=CGa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Jq&&g.Bb(a.Jq,function(f,h){t4(d,h,f)});
t4(d,"VER",a.Km);q5(a,d);return d},LHa=function(){},MHa=function(){this.i=[];
this.l=[]},NHa=function(a,b){this.action=a;
this.params=b||{}},w5=function(a,b){g.B.call(this);
this.i=new g.D(this.qP,0,this);g.C(this,this.i);this.Gf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.z)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},x5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.Z=a;this.G=b;this.u=new g.Kn;this.l=new w5(this.rQ,this);this.i=null;this.U=!1;this.C=null;this.T="";this.K=this.B=0;this.I=[];this.ba=c;this.V=d;this.fa=e},OHa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Dv,sessionId:a.i.l,arrayId:a.i.Vo}},PHa=function(a,b){a.K=b||0;
a.l.stop();y5(a);a.i&&(3==a.i.getState()&&HHa(a.i),CHa(a.i));a.K=0},z5=function(a){return!!a.i&&3==a.i.getState()},y5=function(a){if(a.i){var b=a.V(),c=a.i.Ki||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Ki=c}},A5=function(a){this.scheme="https";
this.port=this.domain="";this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.ud(4,a))||"";b&&(this.port=":"+b);this.domain=g.vd(a)||"";a=g.Qc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.yc(a,"10.0")&&(this.l=!1))},B5=function(a,b){var c=a.i;
a.l&&(c=a.scheme+"://"+a.domain+a.port+a.i);return g.Jd(c+b,{})},C5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.B,d,!0),onError:g.Qa(a.u,e),onTimeout:g.Qa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.uq(b,a)},THa=function(){var a=QHa;
RHa();D5.push(a);SHa()},E5=function(a,b){RHa();
var c=UHa(a,String(b));g.fb(D5)?VHa(c):(SHa(),g.zb(D5,function(d){d(c)}))},RHa=function(){D5||(D5=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",D5,void 0))},VHa=function(a){var b=(F5+1)%50;
F5=b;G5[b]=a;H5||(H5=49==b)},SHa=function(){var a=D5;
if(G5[0]){var b=H5?F5:-1;do{b=(b+1)%50;var c=G5[b];g.zb(a,function(d){d(c)})}while(b!=F5);
G5=Array(50);F5=-1;H5=!1}},UHa=function(a,b){var c=(g.A()-WHa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},I5=function(a){g.N.call(this);
this.G=a;this.screens=[]},XHa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},YHa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ie(a.screens,function(f){return!!F4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=XHa(a,b[d])||c;return c},ZHa=function(a,b){var c=a.screens.length;
a.screens=g.Ie(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},J5=function(a,b,c,d){g.N.call(this);
this.u=a;this.G=b;this.B=c;this.C=d;this.l=0;this.i=null;this.bb=NaN},L5=function(a){I5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;K5(this);this.info("Initializing with "+D4(this.screens))},$Ha=function(a){if(a.screens.length){var b=g.Kc(a.screens,function(d){return d.id}),c=B5(a.l,"/pairing/get_lounge_token_batch");
C5(a.l,c,{screen_ids:b.join(",")},(0,g.z)(a.vL,a),(0,g.z)(a.uL,a))}},K5=function(a){if(g.To("deprecate_pair_servlet_enabled"))return YHa(a,[]);
var b=IGa(OGa());b=g.Ie(b,function(c){return!c.uuid});
return YHa(a,b)},M5=function(a,b){QGa(g.Kc(a.screens,GGa));
b&&PGa()},O5=function(a,b){g.N.call(this);
this.G=b;var c=g.Au("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.G(),f=0,h=e.length;f<h;++f){var l=e[f].id;d[l]=g.eb(c,l)}this.i=d;this.C=a;this.u=this.B=NaN;this.l=null;N5("Initialized with "+g.Qj(this.i))},P5=function(a,b,c){var d=B5(a.C,"/pairing/get_screen_availability");
C5(a.C,d,{lounge_token:b.token},(0,g.z)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},Q5=function(a,b){a:if(w4(b)!=w4(a.i))var c=!1;
else{c=g.Ib(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(N5("Updated online screens: "+g.Qj(a.i)),a.i=b,a.S("screenChange"));aIa(a)},R5=function(a){isNaN(a.u)||g.Fo(a.u);
a.u=g.Do((0,g.z)(a.Cz,a),0<a.B&&a.B<g.A()?2E4:1E4)},N5=function(a){E5("OnlineScreenService",a)},bIa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Cd("Requesting availability of screen w/o lounge token.")});
return b},aIa=function(a){a=g.Ib(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.zu("yt-remote-online-screen-ids",a.join(","),60):g.Bu("yt-remote-online-screen-ids")},S5=function(a){I5.call(this,"ScreenService");
this.B=a;this.i=this.l=null;this.u=[];this.C={};cIa(this)},eIa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Og();if(h=(c?G4(h,c):null)||G4(h,b)){h.uuid=b;var l=T5(a,h);P5(a.i,l,function(m){e(m?l:null)})}else c?dIa(a,c,(0,g.z)(function(m){var n=T5(this,new A4({name:d,
screenId:c,loungeToken:m,dialId:b||""}));P5(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},fIa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},gIa=function(a,b,c){P5(a.i,b,c)},dIa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){var l=h&&h.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.uq(B5(a.B,"/pairing/get_lounge_token_batch"),e)},hIa=function(a){a.screens=a.l.Og();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+D4(a.screens))},cIa=function(a){U5(a);
a.l=new L5(a.B);a.l.subscribe("screenChange",(0,g.z)(a.BL,a));hIa(a);a.u=IGa(g.Au("yt-remote-automatic-screen-cache")||[]);U5(a);a.info("Initializing automatic screens: "+D4(a.u));a.i=new O5(a.B,(0,g.z)(a.Og,a,!0));a.i.subscribe("screenChange",(0,g.z)(function(){this.S("onlineScreenChange")},a))},T5=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=G4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),iIa(a));U5(a);a.C[b.uuid]=b.id;g.zu("yt-remote-device-id-map",a.C,31536E3);return b},iIa=function(a){a=g.Ie(a.u,function(b){return"shortLived"!=b.idType});
g.zu("yt-remote-automatic-screen-cache",g.Kc(a,GGa))},U5=function(a){a.C=g.Au("yt-remote-device-id-map")||{}},V5=function(a,b,c){g.N.call(this);
this.fa=c;this.B=a;this.i=b;this.u=null},W5=function(a,b){a.u=b;
a.S("sessionScreen",a.u)},X5=function(a,b){E5(a.fa,b)},Y5=function(a,b,c){V5.call(this,a,b,"CastSession");
var d=this;this.da=c;this.l=null;this.V=(0,g.z)(this.MJ,this);this.Z=(0,g.z)(this.NP,this);this.U=g.Do(function(){jIa(d,null)},12E4);
this.I=this.C=this.G=this.K=0;this.ba=!1;this.T="unknown"},Z5=function(a,b){g.Fo(a.I);
a.I=0;0==b?kIa(a):a.I=g.Do(function(){kIa(a)},b)},kIa=function(a){lIa(a,"getLoungeToken");
g.Fo(a.C);a.C=g.Do(function(){mIa(a,null)},3E4)},lIa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Qj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ja,(0,g.z)(function(){X5(this,"Failed to send message: "+b+".")},a)):X5(a,"Sending yt message without session: "+g.Qj(c))},$5=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.ED(b,function(c){W5(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},oIa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new A4(b);nIa(a,d,function(e){e?(a.ba=!0,T5(a.B,d),W5(a,d),a.T="unknown",Z5(a,c)):(g.Ao(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},jIa=function(a,b){g.Fo(a.U);
a.U=0;b?a.da.y3&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?oIa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Ao(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),$5(a,b.screenId))):(g.Ao(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),$5(a,b.screenId)):
$5(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},mIa=function(a,b){g.Fo(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.T=c,Z5(a,3E4)):(a.u&&(a.u.token=b.loungeToken,T5(a.B,a.u)),a.S("sessionScreen",a.u),a.ba=!1,a.T="unknown",Z5(a,b.loungeTokenRefreshIntervalMs))},nIa=function(a,b,c,d){g.Fo(a.G);
a.G=0;gIa(a.B,b,function(e){e||0>d?c(e):a.G=g.Do(function(){nIa(a,b,c,d-1)},300)})},pIa=function(a){g.Fo(a.K);
a.K=0;g.Fo(a.G);a.G=0;g.Fo(a.U);a.U=0;g.Fo(a.C);a.C=0;g.Fo(a.I);a.I=0},a6=function(a,b,c){V5.call(this,a,b,"DialSession");
this.C=this.K=null;this.T="";this.Z=c;this.V=null;this.I=g.Ja;this.G=NaN;this.U=(0,g.z)(this.NJ,this);this.l=g.Ja},qIa=function(a){a.l=a.B.DB(a.T,a.i.label,a.i.friendlyName,(0,g.z)(function(b){this.l=g.Ja;
W5(this,b)},a),(0,g.z)(function(b){this.l=g.Ja;
this.Zf(b)},a))},rIa=function(a){var b={};
b.pairingCode=a.T;b.theme=a.Z;TGa()&&(b.env_useStageMdx=1);return g.Hd(b)},b6=function(a,b){V5.call(this,a,b,"ManualSession");
this.l=g.Do((0,g.z)(this.Wo,this,null),150)},c6=function(a,b){g.N.call(this);
this.B=b;this.l=a;this.K=b.appId||"233637DE";this.C=b.theme||"cl";this.T=b.disableCastApi||!1;this.i=null;this.I=!1;this.u=[];this.G=(0,g.z)(this.GO,this)},sIa=function(a,b){return b?g.ab(a.u,function(c){return B4(b,c.label)},a):null},d6=function(a){E5("Controller",a)},QHa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},e6=function(a){return a.I||!!a.u.length||!!a.i},f6=function(a,b,c){b!=a.i&&(g.Zf(a.i),(a.i=b)?(c?a.S("yt-remote-cast2-receiver-resumed",
b.i):a.S("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.z)(a.MF,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Wo(null)):a.S("yt-remote-cast2-session-change",null))},tIa=function(a){var b=a.l.CB(),c=a.i&&a.i.i;
a=g.Kc(b,function(d){c&&B4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=sIa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},zIa=function(a,b,c,d){d.disableCastApi?g6("Cannot initialize because disabled by Mdx config."):uIa()?vIa(b,d)&&(h6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?wIa(a,c):(window.__onGCastApiAvailable=function(e,f){e?wIa(a,c):(i6("Failed to load cast API: "+f),j6(!1),h6(!1),g.Bu("yt-remote-cast-available"),g.Bu("yt-remote-cast-receiver"),
xIa(),c(!1))},d.loadCastApiSetupScript?g.Po("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?$Ga():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?O4():(ZGa(),N4(yIa.map(XGa))))):g6("Cannot initialize because not running Chrome")},xIa=function(){g6("dispose");
var a=k6();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);AIa(!1);g.Lo(l6);l6.length=0},m6=function(){return!!g.Au("yt-remote-cast-installed")},BIa=function(){var a=g.Au("yt-remote-cast-receiver");
return a?a.friendlyName:null},CIa=function(){g6("clearCurrentReceiver");
g.Bu("yt-remote-cast-receiver")},DIa=function(){return m6()?k6()?k6().getCastSession():(i6("getCastSelector: Cast is not initialized."),null):(i6("getCastSelector: Cast API is not installed!"),null)},o6=function(){m6()?k6()?n6()?(g6("Requesting cast selector."),k6().requestSession()):(g6("Wait for cast API to be ready to request the session."),l6.push(g.Ko("yt-remote-cast2-api-ready",o6))):i6("requestCastSelector: Cast is not initialized."):i6("requestCastSelector: Cast API is not installed!")},p6=
function(a,b){n6()?k6().setConnectedScreenStatus(a,b):i6("setConnectedScreenStatus called before ready.")},uIa=function(){var a=0<=g.Qc.search(/ (CrMo|Chrome|CriOS)\//);
return g.EA||a},EIa=function(a,b){k6().init(a,b)},vIa=function(a,b){var c=!1;
k6()||(c=new c6(a,b),c.subscribe("yt-remote-cast2-availability-change",function(d){g.zu("yt-remote-cast-available",d);y4("yt-remote-cast2-availability-change",d)}),c.subscribe("yt-remote-cast2-receiver-selected",function(d){g6("onReceiverSelected: "+d.friendlyName);
g.zu("yt-remote-cast-receiver",d);y4("yt-remote-cast2-receiver-selected",d)}),c.subscribe("yt-remote-cast2-receiver-resumed",function(d){g6("onReceiverResumed: "+d.friendlyName);
g.zu("yt-remote-cast-receiver",d);y4("yt-remote-cast2-receiver-resumed",d)}),c.subscribe("yt-remote-cast2-session-change",function(d){g6("onSessionChange: "+C4(d));
d||g.Bu("yt-remote-cast-receiver");y4("yt-remote-cast2-session-change",d)}),g.Ea("yt.mdx.remote.cloudview.instance_",c,void 0),c=!0);
g6("cloudview.createSingleton_: "+c);return c},k6=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},wIa=function(a,b){j6(!0);
h6(!1);EIa(a,function(c){c?(AIa(!0),g.Mo("yt-remote-cast2-api-ready")):(i6("Failed to initialize cast API."),j6(!1),g.Bu("yt-remote-cast-available"),g.Bu("yt-remote-cast-receiver"),xIa());b(c)})},g6=function(a){E5("cloudview",a)},i6=function(a){E5("cloudview",a)},j6=function(a){g6("setCastInstalled_ "+a);
g.zu("yt-remote-cast-installed",a)},n6=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},AIa=function(a){g6("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},h6=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},q6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.i=null;this.hasNext=this.hj=!1;this.T=this.G=this.l=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},r6=function(a){a.audioTrackId=null;
a.i=null;a.playerState=-1;a.hj=!1;a.hasNext=!1;a.K=0;a.I=g.A();a.C=0;a.l=0;a.G=0;a.T=0;a.B=NaN;a.u=!1},s6=function(a){return a.Ib()?(g.A()-a.I)/1E3:0},t6=function(a,b){a.K=b;
a.I=g.A()},u6=function(a){switch(a.playerState){case 1:case 1081:return(g.A()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},v6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&r6(a)},w6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Sb(a.i);b.hasPrevious=a.hj;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.l;b.duration=a.G;b.loadedTime=a.T;b.liveIngestionTime=a.B;return b},y6=function(a,b){g.N.call(this);
this.Ja=0;this.u=a;this.C=[];this.B=new MHa;this.l=this.i=null;this.K=(0,g.z)(this.iN,this);this.G=(0,g.z)(this.Er,this);this.I=(0,g.z)(this.hN,this);this.T=(0,g.z)(this.pN,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Rz,this),FIa(this))):c=3;0!=c&&(b?this.Rz(c):g.Do((0,g.z)(function(){this.Rz(c)},this),0));
var d=DIa();d&&x6(this,d);this.subscribe("yt-remote-cast2-session-change",this.T)},z6=function(a){return new q6(a.u.getPlayerContextData())},FIa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Qa(this.DO,b),this))},a)},GIa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},A6=function(a){return 1==a.getState()},B6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},D6=function(a,b,c){var d=z6(a);
t6(d,c);-1E3!=d.playerState&&(d.playerState=b);C6(a,d)},E6=function(a,b,c){a.u.sendMessage(b,c)},C6=function(a,b){GIa(a);
a.u.setPlayerContextData(w6(b));FIa(a)},x6=function(a,b){a.l&&(a.l.removeUpdateListener(a.K),a.l.removeMediaListener(a.G),a.Er(null));
a.l=b;a.l&&(E5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.K),a.l.addMediaListener(a.G),a.l.media.length&&a.Er(a.l.media[0]))},HIa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=z6(a);b.contentId!=d.videoId&&E5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;t6(d,a.i.getEstimatedTime());C6(a,d)}else E5("CP","No cast media video. Ignoring state update.")},F6=function(a,b,c){return(0,g.z)(function(d){this.Cd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Cd("Retrying "+b+" using MDx browser channel."),E6(this,b,c))},a)},G6=function(a,b,c){g.N.call(this);
this.C=NaN;this.Z=!1;this.K=this.I=this.U=this.V=NaN;this.T=[];this.B=this.G=this.u=this.Cb=this.i=null;this.fa=a;this.T.push(g.ep(window,"beforeunload",(0,g.z)(this.pL,this)));this.l=[];this.Cb=new q6;this.da=b.id;this.ba=b.idType;this.i=IIa(this,c);this.i.subscribe("handlerOpened",this.mN,this);this.i.subscribe("handlerClosed",this.jN,this);this.i.subscribe("handlerError",this.kN,this);this.i.subscribe("handlerMessage",this.lN,this);this.i.dv(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.Cb.videoId;g.Cu()&&g.zu("yt-remote-session-video-id",d)},this)},H6=function(a){E5("conn",a)},IIa=function(a,b){return new x5(B5(a.fa,"/bc"),b,!1,function(){return a.HB()},"shortLived"==a.ba)},I6=function(a,b){a.S("proxyStateChange",b)},JIa=function(a){a.C=g.Do((0,g.z)(function(){H6("Connecting timeout");
this.xo(1)},a),2E4)},J6=function(a){g.Fo(a.C);
a.C=NaN},K6=function(a){g.Fo(a.V);
a.V=NaN},KIa=function(a){L6(a);
a.U=g.Do((0,g.z)(function(){M6(this,"getNowPlaying")},a),2E4)},L6=function(a){g.Fo(a.U);
a.U=NaN},MIa=function(a,b){b&&(J6(a),K6(a));
var c=z5(a.i)&&isNaN(a.C);b==c?b&&(I6(a,1),M6(a,"getSubtitlesTrack")):b?(a.DD()&&a.Cb.reset(),I6(a,1),M6(a,"getNowPlaying"),LIa(a)):a.xo(1)},NIa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Cb.videoId&&(g.Nb(b.params)?a.Cb.i=null:a.Cb.i=b.params,a.S("remotePlayerChange"))},OIa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Cb.listId=b.params.listId||a.Cb.listId;v6(a.Cb,c,d);a.S("remoteQueueChange")},QIa=function(a,b){b.params=b.params||{};
OIa(a,b);PIa(a,b);a.S("autoplayDismissed")},PIa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
t6(a.Cb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Cb.playerState&&(c=-1E3);a.Cb.playerState=c;c=Number(b.params.loadedTime);a.Cb.T=isNaN(c)?0:c;c=Number(b.params.duration);a.Cb.G=isNaN(c)?0:c;c=a.Cb;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.Cb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.l=isNaN(e)?0:e;1==a.Cb.playerState?KIa(a):L6(a);a.S("remotePlayerChange")},RIa=function(a,b){if(-1E3!=
a.Cb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Cb.playerState=c;c=parseInt(b.params.currentTime,10);t6(a.Cb,isNaN(c)?0:c);a.S("remotePlayerChange")}},SIa=function(a,b){var c="true"==b.params.muted;
a.Cb.volume=parseInt(b.params.volume,10);a.Cb.muted=c;a.S("remotePlayerChange")},TIa=function(a,b){a.G=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},UIa=function(a,b){var c="true"==b.params.hasNext;
a.Cb.hj="true"==b.params.hasPrevious;a.Cb.hasNext=c;a.S("previousNextChange")},LIa=function(a){g.Fo(a.K);
a.K=g.Do((0,g.z)(a.xo,a,1),864E5)},M6=function(a,b,c){c?H6("Sending: action="+b+", params="+g.Qj(c)):H6("Sending: action="+b);
a.i.sendMessage(b,c)},N6=function(a){I5.call(this,"ScreenServiceProxy");
this.Ff=a;this.i=[];this.i.push(this.Ff.$_s("screenChange",(0,g.z)(this.RJ,this)));this.i.push(this.Ff.$_s("onlineScreenChange",(0,g.z)(this.kO,this)))},YIa=function(a,b){SGa();
if(!M4||!M4.get("yt-remote-disable-remote-module-for-dev")){b=g.L("MDX_CONFIG")||b;KGa();K4();O6||(O6=new A5(b?b.loungeApiHost:void 0),TGa()&&(O6.i="/api/loungedev"));P6||(P6=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",P6,void 0));VIa();var c=Q6();if(!c){var d=new S5(O6);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=Q6();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,disableCastApi:b.disableCastApi,
enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});zIa(a,d,function(h){h?R6()&&p6(R6(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){y4("yt-remote-receiver-availability-change")})},e)}if(b&&!g.Ia("yt.mdx.remote.initialized_")){g.Ea("yt.mdx.remote.initialized_",!0,void 0);
S6("Initializing: "+g.Qj(b));T6.push(g.Ko("yt-remote-cast2-availability-change",function(){y4("yt-remote-receiver-availability-change")}));
T6.push(g.Ko("yt-remote-cast2-receiver-selected",function(){U6(null);y4("yt-remote-auto-connect","cast-selector-receiver")}));
T6.push(g.Ko("yt-remote-cast2-receiver-resumed",function(){y4("yt-remote-receiver-resumed","cast-selector-receiver")}));
T6.push(g.Ko("yt-remote-cast2-session-change",WIa));T6.push(g.Ko("yt-remote-connection-change",function(h){h?p6(R6(),"YouTube TV"):V6()||(p6(null,null),CIa())}));
e=W6();b.isAuto&&(e.id+="#dial");g.To("desktop_enable_autoplay")&&(e.capabilities=["atp"]);e.name=b.device;e.app=b.app;var f=b.theme;f&&(e.theme=f);S6(" -- with channel params: "+g.Qj(e));e?(g.zu("yt-remote-session-app",e.app),g.zu("yt-remote-session-name",e.name)):(g.Bu("yt-remote-session-app"),g.Bu("yt-remote-session-name"));g.Ea("yt.mdx.remote.channelParams_",e,void 0);c.start();R6()||XIa()}}},ZIa=function(){var a=Q6().Ff.$_gos();
var b=X6();b&&Y6()&&(F4(a,b)||a.push(b));return JGa(a)},Z6=function(){var a=$Ia();
!a&&m6()&&BIa()&&(a={key:"cast-selector-receiver",name:BIa()});return a},$Ia=function(){var a=ZIa(),b=X6();
b||(b=V6());return g.ab(a,function(c){return b&&B4(b,c.key)?!0:!1})},X6=function(){var a=R6();
if(!a)return null;var b=Q6().Og();return G4(b,a)},WIa=function(a){S6("remote.onCastSessionChange_: "+C4(a));
if(a){var b=X6();if(b&&b.id==a.id){if(p6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))$6&&($6.token=a),(b=Y6())&&b.dv(a)}else b&&a7(),b7(a,1)}else Y6()&&a7()},a7=function(){n6()?k6().stopSession():i6("stopSession called before API ready.");
var a=Y6();a&&(a.disconnect(1),c7(null))},d7=function(){var a=Y6();
return!!a&&3!=a.getProxyState()},S6=function(a){E5("remote",a)},Q6=function(){if(!e7){var a=g.Ia("yt.mdx.remote.screenService_");
e7=a?new N6(a):null}return e7},R6=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},aJa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},bJa=function(){return g.Ia("yt.mdx.remote.connectData_")},U6=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},Y6=function(){return g.Ia("yt.mdx.remote.connection_")},c7=function(a){var b=Y6();
U6(null);a||aJa("");g.Ea("yt.mdx.remote.connection_",a,void 0);P6&&(g.zb(P6,function(c){c(a)}),P6.length=0);
b&&!a?y4("yt-remote-connection-change",!1):!b&&a&&y4("yt-remote-connection-change",!0)},V6=function(){var a=g.Cu();
if(!a)return null;var b=Q6();if(!b)return null;b=b.Og();return G4(b,a)},b7=function(a,b){R6();
X6()&&X6();if(f7)$6=a;else{aJa(a.id);var c=new G6(O6,a,W6());c.connect(b,bJa());c.subscribe("beforeDisconnect",function(d){y4("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){Y6()&&(Y6(),c7(null))});
c.subscribe("browserChannelAuthError",function(){var d=X6();d&&"shortLived"==d.idType&&(n6()?k6().handleBrowserChannelAuthError():i6("refreshLoungeToken called before API ready."))});
c7(c)}},XIa=function(){var a=V6();
a?(S6("Resume connection to: "+C4(a)),b7(a,0)):(L4(),CIa(),S6("Skipping connecting because no session screen found."))},VIa=function(){var a=W6();
if(g.Nb(a)){a=J4();var b=g.Au("yt-remote-session-name")||"",c=g.Au("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},W6=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},g7=function(a,b,c){g.B.call(this);
var d=this;this.l=a;this.F=b;this.tb=c;this.events=new g.iO(this);this.U=this.events.L(this.F,"onVolumeChange",function(e){cJa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.gL(64);this.i=new g.D(this.SG,500,this);this.u=new g.D(this.TG,1E3,this);this.K=new P4(this.fR,0,this);this.B={};this.T=new g.D(this.uH,1E3,this);this.I=new Q4(this.seekTo,1E3,this);this.V=g.Ja;g.C(this,this.events);this.events.L(b,"onCaptionsTrackListChanged",this.TN);this.events.L(b,"captionschanged",this.fN);this.events.L(b,"captionssettingschanged",this.XG);this.events.L(b,"videoplayerreset",this.Mu);this.events.L(b,"mdxautoplaycancel",function(){d.tb.WC()});
a=this.tb;a.ka();a.subscribe("proxyStateChange",this.HF,this);a.subscribe("remotePlayerChange",this.Kr,this);a.subscribe("remoteQueueChange",this.Mu,this);a.subscribe("previousNextChange",this.EF,this);a.subscribe("nowAutoplaying",this.zF,this);a.subscribe("autoplayDismissed",this.ZE,this);g.C(this,this.i);g.C(this,this.u);g.C(this,this.K);g.C(this,this.T);g.C(this,this.I);this.XG();this.Mu();this.Kr()},cJa=function(a,b){if(h7(a)){a.tb.unsubscribe("remotePlayerChange",a.Kr,a);
var c=Math.round(b.volume),d=!!b.muted,e=z6(a.tb);if(c!==e.volume||d!==e.muted)a.tb.setVolume(c,d),a.T.start();a.tb.subscribe("remotePlayerChange",a.Kr,a)}},dJa=function(a){a.xb(0);
a.i.stop();a.qb(new g.gL(64))},i7=function(a,b){if(h7(a)&&!a.C){var c=null;
b&&(c={style:a.F.getSubtitlesUserSettings()},g.Vb(c,b));a.tb.GB(a.F.getVideoData(1).videoId,c);a.B=z6(a.tb).i}},j7=function(a,b){var c=a.F.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.F.getVideoData(1);a.tb.playVideo(c.videoId,b,d,e,c.playerParams,c.fa,wGa(c));a.qb(new g.gL(1))},eJa=function(a,b){if(b){var c=a.F.getOption("captions","tracklist",{YD:1});
c&&c.length?(a.F.setOption("captions","track",b),a.C=!1):(a.F.loadModule("captions"),a.C=!0)}else a.F.setOption("captions","track",{})},h7=function(a){return z6(a.tb).videoId===a.F.getVideoData(1).videoId},k7=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-manual-pairing-popup-dialog",R:{role:"dialog"},N:[{D:"div",J:"ytp-mdx-manual-pairing-popup-dialog-inner-content",N:[{D:"div",J:"ytp-mdx-manual-pairing-popup-title",Y:"Connecting to your TV on web using a code will be going away soon"},{D:"div",J:"ytp-mdx-manual-pairing-popup-buttons",N:[{D:"button",ga:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],Y:"Learn more"},{D:"button",ga:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],Y:"OK"}]}]}]});this.i=new g.PM(this,250);this.learnMoreButton=
this.ea("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.ea("ytp-mdx-manual-pairing-popup-ok");g.C(this,this.i);this.L(this.learnMoreButton,"click",this.l);this.L(this.okButton,"click",this.u)},l7=function(){g.U.call(this,{D:"div",
J:"ytp-mdx-popup-dialog",R:{role:"dialog"},N:[{D:"div",J:"ytp-mdx-popup-dialog-inner-content",N:[{D:"div",J:"ytp-mdx-popup-title",Y:"You're signed out"},{D:"div",J:"ytp-mdx-popup-description",Y:"Videos that you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",J:"ytp-mdx-privacy-popup-buttons",N:[{D:"button",ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],Y:"Cancel"},{D:"button",ga:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],Y:"Confirm"}]}]}]});this.i=new g.PM(this,250);this.cancelButton=this.ea("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.ea("ytp-mdx-privacy-popup-confirm");g.C(this,this.i);this.L(this.cancelButton,"click",this.l);this.L(this.confirmButton,"click",this.u)},m7=function(a){g.U.call(this,{D:"div",
J:"ytp-remote",N:[{D:"div",J:"ytp-remote-display-status",N:[{D:"div",J:"ytp-remote-display-status-icon",N:[g.Ima()]},{D:"div",J:"ytp-remote-display-status-text",Y:"{{statustext}}"}]}]});this.api=a;this.i=new g.PM(this,250);g.C(this,this.i);this.L(a,"presentingplayerstatechange",this.l);fJa(this,a.Sa())},fJa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.HK("Error on $RECEIVER_NAME",c):b.Ib()||g.T(b,4)?g.HK("Playing on $RECEIVER_NAME",c):g.HK("Connected to $RECEIVER_NAME",c);a.wa("statustext",c);a.i.show()}else a.i.hide()},n7=function(a,b){g.ER.call(this,"Play on",0,a,b);
this.F=a;this.Pl={};this.L(a,"onMdxReceiversChange",this.C);this.L(a,"presentingplayerstatechange",this.C);this.C()},o7=function(a){g.sO.call(this,a);
this.fi={key:E4(),name:"This computer"};this.oh=null;this.subscriptions=[];this.qz=this.tb=null;this.Pl=[this.fi];this.fl=this.fi;this.Jc=new g.gL(64);this.vE=0;this.Ke=-1;this.bp=null;this.Mr=this.ru=!1;this.xn=this.vp=null;if(!g.UC(this.player.P())){a=this.player;var b=g.XN(a);b&&(b=b.an())&&(b=new n7(a,b),g.C(this,b));b=new m7(a);g.C(this,b);g.gO(a,b.element,4);this.vp=new l7;g.C(this,this.vp);g.gO(a,this.vp.element,4);g.P(this.player.P().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.P(this.player.P().experiments,"deprecate_pair_servlet_enabled")&&(this.bp=new k7,g.C(this,this.bp),g.gO(a,this.bp.element,4));this.Mr=!!V6();this.ru=!!g.Au("yt-remote-manual-pairing-warning-shown")}},p7=function(a){a.xn&&(a.player.removeEventListener("presentingplayerstatechange",a.xn),a.xn=null)},gJa=function(a,b,c){a.Jc=c;
a.player.S("presentingplayerstatechange",new g.nK(c,b))},hJa=function(a,b,c){var d=!1;
1===b?d=!a.Mr:2===b&&(d=!a.ru);d&&g.pK(c,8)&&(a.player.pauseVideo(),p7(a))},q7=function(a,b){if(b.key!==a.fl.key)if(b.key===a.fi.key)a7();
else{if(a.bp&&!a.ru&&b!==a.fi&&"cast-selector-receiver"!==b.key&&g.nD(a.player.P()))iJa(a);else{var c;(c=!g.P(a.player.P().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Mr||!a.vp);(c?0:g.nD(a.player.P())||g.rD(a.player.P()))&&jJa(a)}a.fl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.P().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.Ka(l).videoId}else h=[e];f=a.player.getCurrentTime(1);d={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.fa,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=wGa(c))&&(d.locationInfo=c);c=d}S6("Connecting to: "+g.Qj(b));"cast-selector-receiver"==b.key?(U6(c||null),c=c||null,
n6()?k6().setLaunchParams(c):i6("setLaunchParams called before ready.")):!c&&d7()&&R6()==b.key?y4("yt-remote-connection-change",!0):(a7(),U6(c||null),c=Q6().Og(),(c=G4(c,b.key))&&b7(c,1))}},jJa=function(a){a.player.Sa().Ib()?a.player.pauseVideo():(a.xn=function(b){hJa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.xn));
a.vp&&a.vp.zc();Y6()||(f7=!0)},iJa=function(a){a.player.Sa().Ib()?a.player.pauseVideo():(a.xn=function(b){hJa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.xn));
a.bp&&a.bp.zc();Y6()||(f7=!0)},jHa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},e5={"'":"\\'"},kJa={},FGa={cS:"atp",o1:"ska",n0:"que",vZ:"mus",n1:"sus",PV:"dsp",F0:"seq",aZ:"mic",PU:"dpa"},M4,I4="",YGa=UGa("loadCastFramework")||UGa("loadCastApplicationFramework"),yIa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(P4,g.B);g.k=P4.prototype;g.k.GJ=function(a){this.B=arguments;this.i=!1;this.bb?this.u=g.A()+this.Gf:this.bb=g.Mm(this.C,this.Gf)};
g.k.stop=function(){this.bb&&(g.v.clearTimeout(this.bb),this.bb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.aa=function(){this.stop();P4.Bd.aa.call(this)};
g.k.HJ=function(){this.u?(this.bb=g.Mm(this.C,this.u-g.A()),this.u=null):(this.bb=null,this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B)))};g.u(Q4,g.B);g.k=Q4.prototype;g.k.yB=function(a){this.u=arguments;this.bb||this.l?this.i=!0:R4(this)};
g.k.stop=function(){this.bb&&(g.v.clearTimeout(this.bb),this.bb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.bb||(this.i=!1,R4(this))};
g.k.aa=function(){g.B.prototype.aa.call(this);this.stop()};T4.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
T4.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};var V4=new g.bm;g.u(aHa,g.Il);X4.prototype.i=null;X4.prototype.getOptions=function(){var a;(a=this.i)||(a={},cHa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var r7;g.Sa(bHa,X4);r7=new bHa;g.k=Y4.prototype;g.k.mm=null;g.k.zi=!1;g.k.Op=null;g.k.BA=null;g.k.yp=null;g.k.Ip=null;g.k.Xk=null;g.k.Rl=null;g.k.yn=null;g.k.ze=null;g.k.Hs=0;g.k.Di=null;g.k.Fv=null;g.k.Rk=null;g.k.fq=-1;g.k.GG=!0;g.k.Jm=!1;g.k.ww=0;g.k.Tu=null;var hHa={},a5={};g.k=Y4.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.gQ=function(a){a=a.target;var b=this.Tu;b&&3==j5(a)?b.yB():this.EH(a)};
g.k.EH=function(a){try{if(a==this.ze)a:{var b=j5(this.ze),c=this.ze.G,d=this.ze.getStatus();if(g.we&&!g.Zd(10)||g.ye&&!g.Yd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.zg&&!l5(this.ze))break a;this.Jm||4!=b||7==c||(8==c||0>=d?this.i.ii(3):this.i.ii(2));f5(this);var e=this.ze.getStatus();this.fq=e;var f=l5(this.ze);(this.zi=200==e)?(4==b&&c5(this),this.G?(iHa(this,b,f),g.zg&&this.zi&&3==b&&(this.B.va(this.u,"tick",this.ZP),this.u.start())):b5(this,f),this.zi&&!this.Jm&&(4==b?this.i.Ws(this):(this.zi=
!1,$4(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Rk=3,W4(13)):(this.Rk=0,W4(14)),c5(this),d5(this))}}catch(h){this.ze&&l5(this.ze)}finally{}};
g.k.ZP=function(){var a=j5(this.ze),b=l5(this.ze);this.Hs<b.length&&(f5(this),iHa(this,a,b),this.zi&&4!=a&&$4(this))};
g.k.yP=function(a){U4((0,g.z)(this.xP,this,a),0)};
g.k.xP=function(a){this.Jm||(f5(this),b5(this,a),$4(this))};
g.k.RF=function(a){U4((0,g.z)(this.wP,this,a),0)};
g.k.wP=function(a){this.Jm||(c5(this),this.zi=a,this.i.Ws(this),this.i.ii(4))};
g.k.cancel=function(){this.Jm=!0;c5(this)};
g.k.GP=function(){this.Op=null;var a=g.A();0<=a-this.BA?(2!=this.Ip&&this.i.ii(3),c5(this),this.Rk=2,W4(18),d5(this)):lHa(this,this.BA-a)};
g.k.getLastError=function(){return this.Rk};g.Sa(h5,g.bm);var sHa=/^https?$/i,lJa=["POST","PUT"];g.k=h5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.T+"; newUri="+a);b=b?b.toUpperCase():"GET";this.T=a;this.u="";this.G=0;this.xa=b;this.da=!1;this.B=!0;this.i=this.ba?dHa(this.ba):dHa(r7);this.Z=this.ba?this.ba.getOptions():r7.getOptions();this.i.onreadystatechange=(0,g.z)(this.FF,this);try{x4(k5(this,"Opening Xhr")),this.ha=!0,this.i.open(b,String(a),!0),this.ha=!1}catch(f){x4(k5(this,"Error opening Xhr: "+f.message));rHa(this,f);return}a=
c||"";var e=this.headers.clone();d&&BGa(d,function(f,h){e.set(h,f)});
d=g.ab(e.wh(),pHa);c=g.v.FormData&&a instanceof g.v.FormData;!g.eb(lJa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Aa&&(this.i.responseType=this.Aa);"withCredentials"in this.i&&this.i.withCredentials!==this.fa&&(this.i.withCredentials=this.fa);try{uHa(this),0<this.I&&(this.V=oHa(this.i),x4(k5(this,"Will abort after "+this.I+"ms if incomplete, xhr2 "+this.V)),this.V?(this.i.timeout=this.I,this.i.ontimeout=(0,g.z)(this.AB,this)):this.U=g.Mm(this.AB,this.I,this)),x4(k5(this,"Sending request")),this.K=!0,this.i.send(a),this.K=!1}catch(f){x4(k5(this,"Send error: "+f.message)),rHa(this,f)}};
g.k.AB=function(){"undefined"!=typeof g.y_&&this.i&&(this.u="Timed out after "+this.I+"ms, aborting",this.G=8,k5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(k5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),i5(this))};
g.k.aa=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),i5(this,!0));h5.Bd.aa.call(this)};
g.k.FF=function(){this.ka()||(this.ha||this.K||this.C?tHa(this):this.FO())};
g.k.FO=function(){tHa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==j5(this)};
g.k.getStatus=function(){try{return 2<j5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=vHa.prototype;g.k.xw=null;g.k.Cg=null;g.k.Uu=!1;g.k.BB=null;g.k.Bt=null;g.k.Ly=null;g.k.yw=null;g.k.Ja=null;g.k.Oj=-1;g.k.gq=null;g.k.qq=null;g.k.connect=function(a){this.yw=a;a=m5(this.i,null,this.yw);W4(3);this.BB=g.A();var b=this.i.I;null!=b?(this.gq=b[0],(this.qq=b[1])?(this.Ja=1,wHa(this)):(this.Ja=2,o5(this))):(v4(a,"MODE","init"),this.Cg=new Y4(this,void 0,void 0,void 0),this.Cg.mm=this.xw,Z4(this.Cg,a,!1,null,!0),this.Ja=0)};
g.k.zK=function(a){if(a)this.Ja=2,o5(this);else{W4(4);var b=this.i;b.Li=b.bl.Oj;v5(b,9)}a&&this.ii(2)};
g.k.zx=function(a){return this.i.zx(a)};
g.k.abort=function(){this.Cg&&(this.Cg.cancel(),this.Cg=null);this.Oj=-1};
g.k.zB=function(){return!1};
g.k.IF=function(a,b){this.Oj=a.fq;if(0==this.Ja)if(b){try{var c=this.l.parse(b)}catch(d){c=this.i;c.Li=this.Oj;v5(c,2);return}this.gq=c[0];this.qq=c[1]}else c=this.i,c.Li=this.Oj,v5(c,2);else if(2==this.Ja)if(this.Uu)W4(7),this.Ly=g.A();else if("11111"==b){if(W4(6),this.Uu=!0,this.Bt=g.A(),c=this.Bt-this.BB,!g.we||g.Zd(10)||500>c)this.Oj=200,this.Cg.cancel(),W4(12),n5(this.i,this,!0)}else W4(8),this.Bt=this.Ly=g.A(),this.Uu=!1};
g.k.Ws=function(){this.Oj=this.Cg.fq;if(this.Cg.zi)0==this.Ja?this.qq?(this.Ja=1,wHa(this)):(this.Ja=2,o5(this)):2==this.Ja&&((!g.we||g.Zd(10)?!this.Uu:200>this.Ly-this.Bt)?(W4(11),n5(this.i,this,!1)):(W4(12),n5(this.i,this,!0)));else{0==this.Ja?W4(9):2==this.Ja&&W4(10);var a=this.i;this.Cg.getLastError();a.Li=this.Oj;v5(a,2)}};
g.k.hs=function(){return this.i.hs()};
g.k.isActive=function(){return this.i.isActive()};
g.k.ii=function(a){this.i.ii(a)};g.k=p5.prototype;g.k.Ki=null;g.k.Jq=null;g.k.ng=null;g.k.Wd=null;g.k.zw=null;g.k.Ct=null;g.k.qC=null;g.k.Xs=null;g.k.Cr=0;g.k.vM=0;g.k.wf=null;g.k.ol=null;g.k.Rj=null;g.k.Rm=null;g.k.bl=null;g.k.Dv=null;g.k.Vo=-1;g.k.uE=-1;g.k.Li=-1;g.k.Bo=0;g.k.ko=0;g.k.Km=8;g.Sa(yHa,g.Il);g.Sa(zHa,g.Il);g.k=p5.prototype;g.k.connect=function(a,b,c,d,e){W4(0);this.zw=b;this.Jq=c||{};d&&void 0!==e&&(this.Jq.OSID=d,this.Jq.OAID=e);this.C?(U4((0,g.z)(this.IC,this,a),100),DHa(this)):this.IC(a)};
g.k.IC=function(a){this.bl=new vHa(this);this.bl.xw=this.Ki;this.bl.l=this.B;this.bl.connect(a)};
g.k.zB=function(){return 0==this.Ja};
g.k.getState=function(){return this.Ja};
g.k.PF=function(a){this.ol=null;HHa(this,a)};
g.k.OF=function(){this.Rj=null;this.Wd=new Y4(this,this.l,"rpc",this.G);this.Wd.mm=this.Ki;this.Wd.ww=0;var a=this.qC.clone();t4(a,"RID","rpc");t4(a,"SID",this.l);t4(a,"CI",this.Dv?"0":"1");t4(a,"AID",this.Vo);q5(this,a);if(!g.we||g.Zd(10))t4(a,"TYPE","xmlhttp"),Z4(this.Wd,a,!0,this.Xs,!1);else{t4(a,"TYPE","html");var b=this.Wd,c=!!this.Xs;b.Ip=3;b.Xk=u4(a.clone());kHa(b,c)}};
g.k.IF=function(a,b){if(0!=this.Ja&&(this.Wd==a||this.ng==a))if(this.Li=a.fq,this.ng==a&&3==this.Ja)if(7<this.Km){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Rj){if(this.Wd)if(this.Wd.yp+3E3<this.ng.yp)s5(this),this.Wd.cancel(),this.Wd=null;else break a;u5(this);W4(19)}}else this.uE=c[1],0<this.uE-this.Vo&&37500>c[2]&&this.Dv&&0==this.ko&&!this.Rm&&(this.Rm=U4((0,g.z)(this.bN,this),6E3));else v5(this,11)}else b!=kJa.EU.i&&v5(this,11);else if(this.Wd==
a&&s5(this),!g.nc(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Vo=e[0];e=e[1];2==this.Ja?"c"==e[0]?(this.l=e[1],this.Xs=e[2],e=e[3],null!=e?this.Km=e:this.Km=6,this.Ja=3,this.wf&&this.wf.EC(),this.qC=m5(this,this.hs()?this.Xs:null,this.zw),IHa(this)):"stop"==e[0]&&v5(this,7):3==this.Ja&&("stop"==e[0]?v5(this,7):"noop"!=e[0]&&this.wf&&this.wf.DC(e),this.ko=0)}}};
g.k.bN=function(){null!=this.Rm&&(this.Rm=null,this.Wd.cancel(),this.Wd=null,u5(this),W4(20))};
g.k.Ws=function(a){if(this.Wd==a){s5(this);this.Wd=null;var b=2}else if(this.ng==a)this.ng=null,b=1;else return;this.Li=a.fq;if(0!=this.Ja)if(a.zi)1==b?(b=V4,b.dispatchEvent(new yHa(b,a.yn?a.yn.length:0,g.A()-a.yp,this.Bo)),r5(this),this.u.length=0):IHa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Li)){if(d=1==b)this.ng||this.ol||1==this.Ja||2<=this.Bo?d=!1:(this.ol=U4((0,g.z)(this.PF,this,a),JHa(this,this.Bo)),this.Bo++,d=!0);d=!(d||2==b&&u5(this))}if(d)switch(c){case 1:v5(this,
5);break;case 4:v5(this,10);break;case 3:v5(this,6);break;case 7:v5(this,12);break;default:v5(this,2)}}};
g.k.UK=function(a){if(!g.eb(arguments,this.Ja))throw Error("Unexpected channel state: "+this.Ja);};
g.k.PQ=function(a){a?W4(2):(W4(1),KHa(this,8))};
g.k.zx=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new h5;a.fa=!1;return a};
g.k.isActive=function(){return!!this.wf&&this.wf.isActive(this)};
g.k.ii=function(a){var b=V4;b.dispatchEvent(new zHa(b,a))};
g.k.hs=function(){return!(!g.we||g.Zd(10))};
g.k=LHa.prototype;g.k.EC=function(){};
g.k.DC=function(){};
g.k.CC=function(){};
g.k.ix=function(){};
g.k.nD=function(){return{}};
g.k.isActive=function(){return!0};g.k=MHa.prototype;g.k.isEmpty=function(){return g.fb(this.i)&&g.fb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.eb(this.i,a)||g.eb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.WAa)(b,a);0<=c?(g.ib(b,c),b=!0):b=!1;return b||g.jb(this.l,a)};
g.k.rg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(w5,g.B);g.k=w5.prototype;g.k.qP=function(){this.Gf=Math.min(3E5,2*this.Gf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Gf+15E3*Math.random();g.ln(this.i,a);this.l=g.A()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Gf=5E3};g.Sa(x5,LHa);g.k=x5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.S=function(a,b){return this.u.S.apply(this.u,arguments)};
g.k.dispose=function(){this.U||(this.U=!0,g.Zf(this.u),PHa(this),g.Zf(this.l),this.l=null,this.V=function(){return""})};
g.k.ka=function(){return this.U};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.T="";this.l.stop();this.C=a||null;this.B=b||0;a=this.Z+"/test";b=this.Z+"/bind";var d=new p5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ba),e=this.i;e&&(e.wf=null);d.wf=this;this.i=d;y5(this);if(this.i){d=g.L("ID_TOKEN");var f=this.i.Ki||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Ki=f}e?(3!=e.getState()&&0==FHa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.Vo)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){var c={_sc:a};b&&g.Vb(c,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.I.push(c):z5(this)&&(y5(this),EHa(this.i,c))};
g.k.EC=function(){this.l.reset();this.C=null;this.B=0;if(this.I.length){var a=this.I;this.I=[];for(var b=0,c=a.length;b<c;++b)EHa(this.i,a[b])}this.S("handlerOpened")};
g.k.CC=function(a){var b=2==a&&401==this.i.Li;4==a||b||this.l.start();this.S("handlerError",a,b)};
g.k.ix=function(a){if(!this.l.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.I.push(d)}};
g.k.nD=function(){var a={v:2};this.T&&(a.gsessionid=this.T);0!=this.B&&(a.ui=""+this.B);0!=this.K&&(a.ui=""+this.K);this.C&&g.Vb(a,this.C);return a};
g.k.DC=function(a){"S"==a[0]?this.T=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),CHa(this.i)):this.S("handlerMessage",new NHa(a[0],a[1]))};
g.k.dv=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.fa&&this.i){var b=this.i.Ki||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Ki=b}};
g.k.rQ=function(){this.l.isActive();0==FHa(this.i)&&this.connect(this.C,this.B)};A5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
A5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
A5.prototype.C=function(a){a(Error("request timed out"))};var WHa=g.A(),D5=null,G5=Array(50),F5=-1,H5=!1;g.Sa(I5,g.N);I5.prototype.Og=function(){return this.screens};
I5.prototype.contains=function(a){return!!F4(this.screens,a)};
I5.prototype.get=function(a){return a?G4(this.screens,a):null};
I5.prototype.info=function(a){E5(this.G,a)};g.u(J5,g.N);g.k=J5.prototype;g.k.start=function(){!this.i&&isNaN(this.bb)&&this.cG()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.bb)||(g.Fo(this.bb),this.bb=NaN)};
g.k.aa=function(){this.stop();g.N.prototype.aa.call(this)};
g.k.cG=function(){this.bb=NaN;this.i=g.uq(B5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.G},timeout:5E3,onSuccess:(0,g.z)(this.JJ,this),onError:(0,g.z)(this.IJ,this),onTimeout:(0,g.z)(this.KJ,this)})};
g.k.JJ=function(a,b){this.i=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.S("pairingComplete",new A4(c))};
g.k.IJ=function(a){this.i=null;a.status&&404==a.status?this.l>=mJa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=mJa[this.l],this.bb=g.Do((0,g.z)(this.cG,this),a),this.l++):this.S("pairingFailed",Error("Server error "+a.status))};
g.k.KJ=function(){this.i=null;this.S("pairingFailed",Error("Server not responding"))};
var mJa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(L5,I5);g.k=L5.prototype;g.k.start=function(){K5(this)&&this.S("screenChange");!g.Au("yt-remote-lounge-token-expiration")&&$Ha(this);g.Fo(this.i);this.i=g.Do((0,g.z)(this.start,this),1E4)};
g.k.add=function(a,b){K5(this);XHa(this,a);M5(this,!1);this.S("screenChange");b(a);a.token||$Ha(this)};
g.k.remove=function(a,b){var c=K5(this);ZHa(this,a)&&(M5(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.k.Bv=function(a,b,c,d){var e=K5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,M5(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.k.aa=function(){g.Fo(this.i);L5.Bd.aa.call(this)};
g.k.vL=function(a){K5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}M5(this,!b);b&&E5(this.G,"Missed "+b+" lounge tokens.")};
g.k.uL=function(a){E5(this.G,"Requesting lounge tokens failed: "+a)};g.u(O5,g.N);g.k=O5.prototype;g.k.start=function(){var a=parseInt(g.Au("yt-remote-fast-check-period")||"0",10);(this.B=g.A()-144E5<a?0:a)?R5(this):(this.B=g.A()+3E5,g.zu("yt-remote-fast-check-period",this.B),this.Cz())};
g.k.isEmpty=function(){return g.Nb(this.i)};
g.k.update=function(){N5("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!G4(a,d)},this);
Q5(this,b)};
g.k.aa=function(){g.Fo(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.N.prototype.aa.call(this)};
g.k.Cz=function(){g.Fo(this.u);this.u=NaN;this.l&&this.l.abort();var a=bIa(this);if(w4(a)){var b=B5(this.C,"/pairing/get_screen_availability");this.l=C5(this.C,b,{lounge_token:g.Ib(a).join(",")},(0,g.z)(this.ZO,this,a),(0,g.z)(this.YO,this))}else Q5(this,{}),R5(this)};
g.k.ZO=function(a,b){this.l=null;var c=g.Ib(bIa(this));if(g.xb(c,g.Ib(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;Q5(this,d);R5(this)}else this.Cd("Changing Screen set during request."),this.Cz()};
g.k.YO=function(a){this.Cd("Screen availability failed: "+a);this.l=null;R5(this)};
g.k.Cd=function(a){E5("OnlineScreenService",a)};g.Sa(S5,I5);g.k=S5.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.S("screenChange"),this.i.isEmpty()||this.S("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Bv=function(a,b,c,d){this.l.contains(a)?this.l.Bv(a,b,c,d):(a="Updating name of unknown screen: "+a.name,E5(this.G,a),d(Error(a)))};
g.k.Og=function(a){return a?this.screens:g.lb(this.screens,g.Ie(this.u,function(b){return!this.contains(b)},this))};
g.k.CB=function(){return g.Ie(this.Og(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.DB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new J5(this.B,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(h){g.Zf(f);d(T5(this,h))},this));
f.subscribe("pairingFailed",function(h){g.Zf(f);e(h)});
f.start();return(0,g.z)(f.stop,f)};
g.k.LJ=function(a,b,c,d){g.uq(B5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(e,f){var h=new A4(f.screen||{});if(!h.name||fIa(this,h.name)){a:{var l=h.name;for(var m=2,n=b(l,m);fIa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}h.name=l}c(T5(this,h))},this),
onError:(0,g.z)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.k.aa=function(){g.Zf(this.l);g.Zf(this.i);S5.Bd.aa.call(this)};
g.k.BL=function(){hIa(this);this.S("screenChange");this.i.update()};
S5.prototype.dispose=S5.prototype.dispose;g.Sa(V5,g.N);g.k=V5.prototype;g.k.getScreen=function(){return this.u};
g.k.Zf=function(a){this.ka()||(a&&X5(this,""+a),this.u=null,this.S("sessionScreen",null))};
g.k.info=function(a){E5(this.fa,a)};
g.k.EB=function(){return null};
g.k.Oz=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){X5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.aa=function(){this.Oz("");V5.Bd.aa.call(this)};g.u(Y5,V5);g.k=Y5.prototype;g.k.Nz=function(a){if(this.l){if(this.l==a)return;X5(this,"Overriding cast session with new session object");pIa(this);this.ba=!1;this.T="unknown";this.l.removeUpdateListener(this.V);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z)}this.l=a;this.l.addUpdateListener(this.V);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z);lIa(this,"getMdxSessionStatus")};
g.k.Wo=function(a){this.info("launchWithParams no-op for Cast: "+g.Qj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.z)(function(){this.Zf()},this),(0,g.z)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.Oz=function(){};
g.k.aa=function(){this.info("disposeInternal");pIa(this);this.l&&(this.l.removeUpdateListener(this.V),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Z));this.l=null;V5.prototype.aa.call(this)};
g.k.NP=function(a,b){if(!this.ka())if(b){var c=S4(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Qj(c));switch(d){case "mdxSessionStatus":jIa(this,c);break;case "loungeToken":mIa(this,c);break;default:X5(this,"Unknown youtube message: "+d)}}else X5(this,"Unable to parse message.")}else X5(this,"No data in message.")};
g.k.ED=function(a,b,c,d){g.Fo(this.K);this.K=0;eIa(this.B,this.i.label,a,this.i.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(X5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.K=g.Do((0,g.z)(this.ED,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.EB=function(){return this.l};
g.k.MJ=function(a){this.ka()||a||(X5(this,"Cast session died."),this.Zf())};g.u(a6,V5);g.k=a6.prototype;g.k.Nz=function(a){this.C=a;this.C.addUpdateListener(this.U)};
g.k.Wo=function(a){this.V=a;this.I()};
g.k.stop=function(){this.l();this.l=g.Ja;g.Fo(this.G);this.C?this.C.stop((0,g.z)(this.Zf,this,null),(0,g.z)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.aa=function(){this.l();this.l=g.Ja;g.Fo(this.G);this.C&&this.C.removeUpdateListener(this.U);this.C=null;V5.prototype.aa.call(this)};
g.k.NJ=function(a){this.ka()||a||(X5(this,"DIAL session died."),this.l(),this.l=g.Ja,this.Zf())};
g.k.zy=function(a){this.T=E4();if(this.V){var b=new chrome.cast.DialLaunchResponse(!0,rIa(this));a(b);qIa(this)}else this.I=(0,g.z)(function(){g.Fo(this.G);this.I=g.Ja;this.G=NaN;var c=new chrome.cast.DialLaunchResponse(!0,rIa(this));a(c);qIa(this)},this),this.G=g.Do((0,g.z)(function(){this.I()},this),100)};
g.k.SL=function(a,b,c){eIa(this.B,this.K.receiver.label,a,this.i.friendlyName,(0,g.z)(function(d){d&&d.token?(W5(this,d),b(new chrome.cast.DialLaunchResponse(!1))):this.zy(b,c)},this),(0,g.z)(function(d){X5(this,"Failed to get DIAL screen: "+d);
this.zy(b,c)},this))};g.u(b6,V5);b6.prototype.stop=function(){this.Zf()};
b6.prototype.Nz=function(){};
b6.prototype.Wo=function(){g.Fo(this.l);this.l=NaN;var a=G4(this.B.Og(),this.i.label);a?W5(this,a):this.Zf(Error("No such screen"))};
b6.prototype.aa=function(){g.Fo(this.l);this.l=NaN;V5.prototype.aa.call(this)};g.u(c6,g.N);g.k=c6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.K);this.T||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.z)(this.JO,this);c=new chrome.cast.ApiConfig(c,(0,g.z)(this.KF,this),f,d,e);c.customDialLaunchCallback=(0,g.z)(this.wN,this);chrome.cast.initialize(c,(0,g.z)(function(){this.ka()||
(chrome.cast.addReceiverActionListener(this.G),THa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.FB,this)),this.u=tIa(this),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.z)(function(h){this.Cd("Failed to set initial custom receivers: "+g.Qj(h))},this)),this.S("yt-remote-cast2-availability-change",e6(this)),b(!0))},this),(0,g.z)(function(h){this.Cd("Failed to initialize API: "+g.Qj(h));
b(!1)},this))};
g.k.yQ=function(a,b){d6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)d6("Unsetting old screen status: "+this.i.i.friendlyName),f6(this,null)}if(a&&b){if(!this.i){c=G4(this.l.Og(),a);if(!c){d6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){d6("setConnectedScreenStatus: Screen with id type to be short lived.");return}var d=sIa(this,c);d||(d6("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(d),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.z)(function(e){this.Cd("Failed to set initial custom receivers: "+g.Qj(e))},this)));
d6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);f6(this,new b6(this.l,d),!0)}this.i.Oz(b)}else d6("setConnectedScreenStatus: no screen.")};
g.k.zQ=function(a){this.ka()?this.Cd("Setting connection data on disposed cast v2"):this.i?this.i.Wo(a):this.Cd("Setting connection data without a session")};
g.k.PJ=function(){this.ka()?this.Cd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),f6(this,null)):d6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.z)(this.KF,this),(0,g.z)(this.cP,this))};
g.k.aa=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.FB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=QHa,b=g.Ia("yt.mdx.remote.debug.handlers_");g.jb(b||[],a);g.Zf(this.i);g.N.prototype.aa.call(this)};
g.k.Cd=function(a){E5("Controller",a)};
g.k.MF=function(a,b){this.i==a&&(b||f6(this,null),this.S("yt-remote-cast2-session-change",b))};
g.k.GO=function(a,b){if(!this.ka())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),d6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)d6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{d6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.S("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:f6(this,
new b6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:f6(this,new a6(this.l,a,this.C));break;case chrome.cast.ReceiverType.CAST:f6(this,new Y5(this.l,a,this.B));break;default:this.Cd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Cd("Stopping receiver w/o session: "+a.friendlyName)}else this.Cd("onReceiverAction_ called without receiver.")};
g.k.wN=function(a){if(this.ka())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Cd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Cd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return d6("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Cd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);f6(this,new a6(this.l,b,this.C))}b=this.i;b.K=a;return b.K.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.z)(b.SL,b,(b.K.extraData||{}).screenId||null)):new Promise((0,g.z)(b.zy,b))};
g.k.KF=function(a){if(!this.ka()){d6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)d6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),f6(this,new Y5(this.l,b,this.B),!0);else{this.Cd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=G4(this.l.Og(),c.label);d&&B4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(d6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Zf(this.i),this.i=new Y5(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.z)(this.MF,this,this.i)),this.i.Wo(null));this.i.Nz(a)}}};
g.k.OJ=function(){return this.i?this.i.EB():null};
g.k.cP=function(a){this.ka()||(this.Cd("Failed to estabilish a session: "+g.Qj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&f6(this,null))};
g.k.JO=function(a){d6("Receiver availability updated: "+a);if(!this.ka()){var b=e6(this);this.I=a==chrome.cast.ReceiverAvailability.AVAILABLE;e6(this)!=b&&this.S("yt-remote-cast2-availability-change",e6(this))}};
g.k.FB=function(){this.ka()||(this.u=tIa(this),d6("Updating custom receivers: "+g.Qj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ja,(0,g.z)(function(){this.Cd("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",e6(this)))};
c6.prototype.setLaunchParams=c6.prototype.zQ;c6.prototype.setConnectedScreenStatus=c6.prototype.yQ;c6.prototype.stopSession=c6.prototype.PJ;c6.prototype.getCastSession=c6.prototype.OJ;c6.prototype.requestSession=c6.prototype.requestSession;c6.prototype.init=c6.prototype.init;c6.prototype.dispose=c6.prototype.dispose;var l6=[];g.k=q6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";r6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.i=a.trackData,this.hj=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.l=a.seekableEnd,this.G=a.duration,this.T=a.loadedTime,this.B=a.liveIngestionTime,this.u=!isNaN(this.B))};
g.k.Ib=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.u?this.G+s6(this):this.G};
g.k.clone=function(){return new q6(w6(this))};g.u(y6,g.N);g.k=y6.prototype;g.k.getState=function(){return this.Ja};
g.k.play=function(){A6(this)?(this.i?this.i.play(null,g.Ja,F6(this,"play")):E6(this,"play"),D6(this,1,u6(z6(this))),this.S("remotePlayerChange")):B6(this,this.play)};
g.k.pause=function(){A6(this)?(this.i?this.i.pause(null,g.Ja,F6(this,"pause")):E6(this,"pause"),D6(this,2,u6(z6(this))),this.S("remotePlayerChange")):B6(this,this.pause)};
g.k.seekTo=function(a){if(A6(this)){if(this.i){var b=z6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ib()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ja,F6(this,"seekTo",{newTime:a}))}else E6(this,"seekTo",{newTime:a});D6(this,3,a);this.S("remotePlayerChange")}else B6(this,g.Qa(this.seekTo,a))};
g.k.stop=function(){if(A6(this)){this.i?this.i.stop(null,g.Ja,F6(this,"stopVideo")):E6(this,"stopVideo");var a=z6(this);a.index=-1;a.videoId="";r6(a);C6(this,a);this.S("remotePlayerChange")}else B6(this,this.stop)};
g.k.setVolume=function(a,b){if(A6(this)){var c=z6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.z)(function(){E5("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Cd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.z)(function(){E5("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Cd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);E6(this,"setVolume",e)}c.muted=b;c.volume=a;C6(this,c)}else B6(this,g.Qa(this.setVolume,a,b))};
g.k.GB=function(a,b){if(A6(this)){var c=z6(this),d={videoId:a};b&&(c.i={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Qj(b.style),g.Vb(d,c.i));E6(this,"setSubtitlesTrack",d);C6(this,c)}else B6(this,g.Qa(this.GB,a,b))};
g.k.setAudioTrack=function(a,b){if(A6(this)){var c=b.getLanguageInfo().getId();E6(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=z6(this);d.audioTrackId=c;C6(this,d)}else B6(this,g.Qa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=z6(this);c=c||0;var m={videoId:a,currentIndex:c};v6(l,a,c);void 0!==b&&(t6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Qj(h));E6(this,"setPlaylist",m);d||C6(this,l)};
g.k.Pu=function(a,b){if(A6(this)){if(a&&b){var c=z6(this);v6(c,a,b);C6(this,c)}E6(this,"previous")}else B6(this,g.Qa(this.Pu,a,b))};
g.k.nextVideo=function(a,b){if(A6(this)){if(a&&b){var c=z6(this);v6(c,a,b);C6(this,c)}E6(this,"next")}else B6(this,g.Qa(this.nextVideo,a,b))};
g.k.WC=function(){A6(this)?E6(this,"dismissAutoplay"):B6(this,this.WC)};
g.k.dispose=function(){if(3!=this.Ja){var a=this.Ja;this.Ja=3;this.S("proxyStateChange",a,this.Ja)}g.N.prototype.dispose.call(this)};
g.k.aa=function(){GIa(this);this.u=null;this.B.clear();x6(this,null);g.N.prototype.aa.call(this)};
g.k.Rz=function(a){if((a!=this.Ja||2==a)&&3!=this.Ja&&0!=a){var b=this.Ja;this.Ja=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.fb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.DO=function(a,b){this.S(a,b)};
g.k.iN=function(a){if(!a)this.Er(null),x6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=z6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)E5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,C6(this,b)}};
g.k.Er=function(a){E5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.I);if(this.i=a)this.i.addUpdateListener(this.I),HIa(this),this.S("remotePlayerChange")};
g.k.hN=function(a){a?(HIa(this),this.S("remotePlayerChange")):this.Er(null)};
g.k.gA=function(){E6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.pN=function(){var a=DIa();a&&x6(this,a)};
g.k.Cd=function(a){E5("CP",a)};g.u(G6,g.N);g.k=G6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.Cb.listId=c);this.Cb.videoId=d;this.Cb.index=h||0;this.Cb.state=3;t6(this.Cb,m);this.B="UNSUPPORTED";H6("Connecting with setPlaylist and params: "+g.Qj(l));this.i.connect({method:"setPlaylist",
params:g.Qj(l)},a,NGa())}else H6("Connecting without params"),this.i.connect({},a,NGa());JIa(this)};
g.k.dv=function(a){this.i.dv(a)};
g.k.dispose=function(){this.ka()||(this.S("beforeDispose"),I6(this,3));g.N.prototype.dispose.call(this)};
g.k.aa=function(){J6(this);L6(this);K6(this);g.Fo(this.I);this.I=NaN;g.Fo(this.K);this.K=NaN;this.u=null;g.fp(this.T);this.T.length=0;this.i.dispose();g.N.prototype.aa.call(this);this.B=this.G=this.l=this.Cb=this.i=null};
g.k.pL=function(){this.xo(2)};
g.k.mN=function(){H6("Channel opened");this.Z&&(this.Z=!1,K6(this),this.V=g.Do((0,g.z)(function(){H6("Timing out waiting for a screen.");this.xo(1)},this),15E3));
RGa(OHa(this.i),this.da)};
g.k.jN=function(){H6("Channel closed");isNaN(this.C)?L4(!0):L4();this.dispose()};
g.k.kN=function(a,b){L4();isNaN(this.dr())?(b&&"shortLived"==this.ba&&this.S("browserChannelAuthError",a),H6("Channel error: "+a+" without reconnection"),this.dispose()):(this.Z=!0,H6("Channel error: "+a+" with reconnection in "+this.dr()+" ms"),I6(this,2))};
g.k.lN=function(a){a.params?H6("Received: action="+a.action+", params="+g.Qj(a.params)):H6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=S4(a.params.devices);this.l=g.Kc(a,function(c){return new z4(c)});
a=!!g.ab(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
MIa(this,a);break;case "loungeScreenDisconnected":g.kb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
MIa(this,!1);break;case "remoteConnected":var b=new z4(S4(a.params.device));g.ab(this.l,function(c){return b?c.id==b.id:!1})||xGa(this.l,b);
break;case "remoteDisconnected":b=new z4(S4(a.params.device));g.kb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":OIa(this,a);break;case "nowPlaying":QIa(this,a);break;case "onStateChange":PIa(this,a);break;case "onAdStateChange":RIa(this,a);break;case "onVolumeChanged":SIa(this,a);break;case "onSubtitlesTrackChanged":NIa(this,a);break;case "nowAutoplaying":TIa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.S("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":UIa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:H6("Unrecognized action: "+a.action)}};
g.k.nQ=function(){if(this.u){var a=this.u;this.u=null;this.Cb.videoId!=a&&M6(this,"getNowPlaying")}};
g.k.kL=function(){var a=3;this.ka()||(a=0,isNaN(this.dr())?z5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.xo=function(a){H6("Disconnecting with "+a);J6(this);this.S("beforeDisconnect",a);1==a&&L4();PHa(this.i,a);this.dispose()};
g.k.iL=function(){var a=this.Cb;this.u&&(a=this.Cb.clone(),v6(a,this.u,a.index));return w6(a)};
g.k.AQ=function(a){var b=new q6(a);b.videoId&&b.videoId!=this.Cb.videoId&&(this.u=b.videoId,g.Fo(this.I),this.I=g.Do((0,g.z)(this.nQ,this),5E3));var c=[];this.Cb.listId==b.listId&&this.Cb.videoId==b.videoId&&this.Cb.index==b.index||c.push("remoteQueueChange");this.Cb.playerState==b.playerState&&this.Cb.volume==b.volume&&this.Cb.muted==b.muted&&u6(this.Cb)==u6(b)&&g.Qj(this.Cb.i)==g.Qj(b.i)||c.push("remotePlayerChange");this.Cb.reset(a);g.zb(c,function(d){this.S(d)},this)};
g.k.DD=function(){var a=this.i.G.id,b=g.ab(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.dr=function(){var a=this.i;return a.l.isActive()?a.l.l-g.A():NaN};
g.k.eL=function(){return this.B||"UNSUPPORTED"};
g.k.fL=function(){return this.G||""};
g.k.QJ=function(){if(!isNaN(this.dr())){var a=this.i.l;g.mn(a.i);a.start()}};
g.k.wQ=function(a,b){M6(this,a,b);LIa(this)};
g.k.HB=function(){var a=g.Bq("SID","")||"",b=g.Bq("SAPISID","")||"",c=g.Bq("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.qf(g.Te(a),2);b=g.qf(g.Te(b),2);c=g.qf(g.Te(c),2);return g.qf(g.Te(a+","+b+","+c),2)};
G6.prototype.subscribe=G6.prototype.subscribe;G6.prototype.unsubscribeByKey=G6.prototype.Mf;G6.prototype.getProxyState=G6.prototype.kL;G6.prototype.disconnect=G6.prototype.xo;G6.prototype.getPlayerContextData=G6.prototype.iL;G6.prototype.setPlayerContextData=G6.prototype.AQ;G6.prototype.getOtherConnectedRemoteId=G6.prototype.DD;G6.prototype.getReconnectTimeout=G6.prototype.dr;G6.prototype.getAutoplayMode=G6.prototype.eL;G6.prototype.getAutoplayVideoId=G6.prototype.fL;G6.prototype.reconnect=G6.prototype.QJ;
G6.prototype.sendMessage=G6.prototype.wQ;G6.prototype.getXsrfToken=G6.prototype.HB;g.u(N6,I5);g.k=N6.prototype;g.k.Og=function(a){return this.Ff.$_gs(a)};
g.k.contains=function(a){return!!this.Ff.$_c(a)};
g.k.get=function(a){return this.Ff.$_g(a)};
g.k.start=function(){this.Ff.$_st()};
g.k.add=function(a,b,c){this.Ff.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ff.$_r(a,b,c)};
g.k.Bv=function(a,b,c,d){this.Ff.$_un(a,b,c,d)};
g.k.aa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ff.$_ubk(this.i[a]);this.i.length=0;this.Ff=null;I5.prototype.aa.call(this)};
g.k.RJ=function(){this.S("screenChange")};
g.k.kO=function(){this.S("onlineScreenChange")};
S5.prototype.$_st=S5.prototype.start;S5.prototype.$_gspc=S5.prototype.LJ;S5.prototype.$_gsppc=S5.prototype.DB;S5.prototype.$_c=S5.prototype.contains;S5.prototype.$_g=S5.prototype.get;S5.prototype.$_a=S5.prototype.add;S5.prototype.$_un=S5.prototype.Bv;S5.prototype.$_r=S5.prototype.remove;S5.prototype.$_gs=S5.prototype.Og;S5.prototype.$_gos=S5.prototype.CB;S5.prototype.$_s=S5.prototype.subscribe;S5.prototype.$_ubk=S5.prototype.Mf;var $6=null,f7=!1,O6=null,P6=null,e7=null,T6=[];g.u(g7,g.B);g.k=g7.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.i.stop();this.u.stop();this.K.stop();this.V();var a=this.tb;a.unsubscribe("proxyStateChange",this.HF,this);a.unsubscribe("remotePlayerChange",this.Kr,this);a.unsubscribe("remoteQueueChange",this.Mu,this);a.unsubscribe("previousNextChange",this.EF,this);a.unsubscribe("nowAutoplaying",this.zF,this);a.unsubscribe("autoplayDismissed",this.ZE,this);this.tb=this.l=null};
g.k.IB=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.tb.Ja)if(h7(this)){if(!z6(this.tb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":z6(this.tb).Ib()?this.tb.pause():this.tb.play();break;case "control_play":this.tb.play();break;case "control_pause":this.tb.pause();break;case "control_seek":this.I.yB(c[0],c[1]);break;case "control_subtitles_set_track":i7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.F.getCurrentTime();j7(this,0===c?void 0:c);break;case "control_seek":j7(this,c[0]);break;case "control_subtitles_set_track":i7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.fN=function(a){this.K.GJ(a)};
g.k.fR=function(a){this.IB("control_subtitles_set_track",g.Nb(a)?null:a)};
g.k.XG=function(){var a=this.F.getOption("captions","track");g.Nb(a)||i7(this,a)};
g.k.xb=function(a){this.l.xb(a,this.F.getVideoData().lengthSeconds)};
g.k.TN=function(){g.Nb(this.B)||eJa(this,this.B);this.C=!1};
g.k.HF=function(a,b){this.u.stop();2===b&&this.TG()};
g.k.Kr=function(){if(h7(this)){this.i.stop();var a=z6(this.tb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Ke=1;break;case 1082:case 1083:this.l.Ke=0;break;default:this.l.Ke=-1}switch(a.playerState){case 1081:case 1:this.qb(new g.gL(8));this.SG();break;case 1085:case 3:this.qb(new g.gL(9));break;case 1083:case 0:this.qb(new g.gL(2));this.I.stop();this.xb(this.F.getVideoData().lengthSeconds);break;case 1084:this.qb(new g.gL(4));break;case 2:this.qb(new g.gL(4));this.xb(u6(a));
break;case -1:this.qb(new g.gL(64));break;case -1E3:this.qb(new g.gL(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=z6(this.tb).i;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,eJa(this,a));a=z6(this.tb);-1===a.volume||Math.round(this.F.getVolume())===a.volume&&this.F.isMuted()===a.muted||this.T.isActive()||this.uH()}else dJa(this)};
g.k.EF=function(){this.F.S("mdxpreviousnextchange")};
g.k.Mu=function(){h7(this)||dJa(this)};
g.k.zF=function(a){isNaN(a)||this.F.S("mdxnowautoplaying",a)};
g.k.ZE=function(){this.F.S("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){h7(this)&&this.tb.setAudioTrack(this.F.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===z6(this.tb).playerState?j7(this,a):b&&this.tb.seekTo(a)};
g.k.uH=function(){var a=this;if(h7(this)){var b=z6(this.tb);this.events.Db(this.U);b.muted?this.F.mute():this.F.unMute();this.F.setVolume(b.volume);this.U=this.events.L(this.F,"onVolumeChange",function(c){cJa(a,c)})}};
g.k.SG=function(){this.i.stop();if(!this.tb.ka()){var a=z6(this.tb);a.Ib()&&this.qb(new g.gL(8));this.xb(u6(a));this.i.start()}};
g.k.TG=function(){this.u.stop();this.i.stop();var a=this.tb.u.getReconnectTimeout();2==this.tb.Ja&&!isNaN(a)&&this.u.start()};
g.k.qb=function(a){this.u.stop();var b=this.G;if(!g.lL(b,a)){var c=g.T(a,2);c!==g.T(this.G,2)&&this.F.An(c);this.G=a;gJa(this.l,b,a)}};g.u(k7,g.U);k7.prototype.zc=function(){this.i.show()};
k7.prototype.fb=function(){this.i.hide()};
k7.prototype.l=function(){g.PK("https://support.google.com/youtube/answer/7640706")};
k7.prototype.u=function(){y4("mdx-manual-pairing-popup-ok");this.fb()};g.u(l7,g.U);l7.prototype.zc=function(){this.i.show()};
l7.prototype.fb=function(){this.i.hide()};
l7.prototype.l=function(){y4("mdx-privacy-popup-cancel");this.fb()};
l7.prototype.u=function(){y4("mdx-privacy-popup-confirm");this.fb()};g.u(m7,g.U);m7.prototype.l=function(a){fJa(this,a.state)};g.u(n7,g.ER);n7.prototype.C=function(){var a=this.F.getOption("remote","receivers");a&&1<a.length&&!this.F.getOption("remote","quickCast")?(this.Pl=g.Ab(a,this.i,this),g.FR(this,g.Kc(a,this.i)),a=this.F.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.fh(a),this.enable(!0)):this.enable(!1)};
n7.prototype.i=function(a){return a.key};
n7.prototype.Ph=function(a){return"cast-selector-receiver"===a?"Cast...":this.Pl[a].name};
n7.prototype.Te=function(a){g.ER.prototype.Te.call(this,a);this.F.setOption("remote","currentReceiver",this.Pl[a]);this.Ya.fb()};g.u(o7,g.sO);g.k=o7.prototype;
g.k.create=function(){var a=this.player.P(),b=g.SC(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.P(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.P(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.P(a.experiments,"enable_cast_short_lived_lounge_token")};YIa(b,a);this.subscriptions.push(g.Ko("yt-remote-before-disconnect",this.dN,this));this.subscriptions.push(g.Ko("yt-remote-connection-change",this.KO,this));this.subscriptions.push(g.Ko("yt-remote-receiver-availability-change",
this.GF,this));this.subscriptions.push(g.Ko("yt-remote-auto-connect",this.IO,this));this.subscriptions.push(g.Ko("yt-remote-receiver-resumed",this.HO,this));this.subscriptions.push(g.Ko("mdx-privacy-popup-confirm",this.cQ,this));this.subscriptions.push(g.Ko("mdx-privacy-popup-cancel",this.bQ,this));this.subscriptions.push(g.Ko("mdx-manual-pairing-popup-ok",this.jM,this));this.GF()};
g.k.load=function(){this.player.cancelPlayback();g.sO.prototype.load.call(this);this.oh=new g7(this,this.player,this.tb);var a=(a=bJa())?a.currentTime:0;var b=d7()?new y6(Y6(),void 0):null;0==a&&b&&(a=u6(z6(b)));0!==a&&this.xb(a);gJa(this,this.Jc,this.Jc);this.player.Hj(6)};
g.k.unload=function(){this.player.S("mdxautoplaycanceled");this.fl=this.fi;g.$f(this.oh,this.tb);this.tb=this.oh=null;g.sO.prototype.unload.call(this);this.player.Hj(5);p7(this)};
g.k.aa=function(){g.Lo(this.subscriptions);g.sO.prototype.aa.call(this)};
g.k.xj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.oh.IB.apply(this.oh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Ke};
g.k.lL=function(){return this.loaded?this.oh.suggestion:null};
g.k.hj=function(){return this.tb?z6(this.tb).hj:!1};
g.k.hasNext=function(){return this.tb?z6(this.tb).hasNext:!1};
g.k.xb=function(a,b){this.vE=a||0;this.player.S("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.vE};
g.k.getProgressState=function(){var a=z6(this.tb),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.P().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Ie():!a.isAdPlaying()&&this.player.Ie(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+s6(a):a.B,isAtLiveHead:1>=(a.u?a.l+s6(a):a.l)-this.getCurrentTime(),loaded:a.T,seekableEnd:a.u?a.l+s6(a):a.l,seekableStart:0<a.C?a.C+
s6(a):a.C}};
g.k.nextVideo=function(){this.tb&&this.tb.nextVideo()};
g.k.Pu=function(){this.tb&&this.tb.Pu()};
g.k.dN=function(a){1===a&&(this.qz=this.tb?z6(this.tb):null)};
g.k.KO=function(){var a=d7()?new y6(Y6(),void 0):null;if(a){var b=this.fl;this.loaded&&this.unload();this.tb=a;this.qz=null;b.key!==this.fi.key&&(this.fl=b,this.load())}else g.Zf(this.tb),this.tb=null,this.loaded&&(this.unload(),(a=this.qz)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,u6(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.GF=function(){var a=[this.fi],b=a.concat,c=ZIa();m6()&&g.Au("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Pl=b.call(a,c);a=Z6()||this.fi;q7(this,a);this.player.ra("onMdxReceiversChange")};
g.k.IO=function(){var a=Z6();q7(this,a)};
g.k.HO=function(){this.fl=Z6()};
g.k.cQ=function(){this.Mr=!0;p7(this);f7=!1;$6&&b7($6,1);$6=null};
g.k.bQ=function(){this.Mr=!1;p7(this);q7(this,this.fi);this.fl=this.fi;f7=!1;$6=null;this.player.playVideo()};
g.k.jM=function(){this.ru=!0;p7(this);g.zu("yt-remote-manual-pairing-warning-shown",!0,2592E3);f7=!1;$6&&b7($6,1);$6=null};
g.k.De=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Pl;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?o6():q7(this,b)),this.loaded?this.fl:this.fi;case "quickCast":return 2===this.Pl.length&&"cast-selector-receiver"===this.Pl[1].key?(b&&o6(),!0):!1}};
g.k.gA=function(){this.tb.gA()};
g.k.xi=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.yO.remote=o7;})(_yt_player);
